// GraphRAG query and result types for proto-canonical operations.
// This file provides types for the QueryNodes and StoreNode RPCs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/graphrag.proto

package graphragpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryScope defines the scope of a graph query.
type QueryScope int32

const (
	QueryScope_QUERY_SCOPE_UNSPECIFIED QueryScope = 0
	QueryScope_QUERY_SCOPE_MISSION     QueryScope = 1
	QueryScope_QUERY_SCOPE_MISSION_RUN QueryScope = 2
	QueryScope_QUERY_SCOPE_GLOBAL      QueryScope = 3
)

// Enum value maps for QueryScope.
var (
	QueryScope_name = map[int32]string{
		0: "QUERY_SCOPE_UNSPECIFIED",
		1: "QUERY_SCOPE_MISSION",
		2: "QUERY_SCOPE_MISSION_RUN",
		3: "QUERY_SCOPE_GLOBAL",
	}
	QueryScope_value = map[string]int32{
		"QUERY_SCOPE_UNSPECIFIED": 0,
		"QUERY_SCOPE_MISSION":     1,
		"QUERY_SCOPE_MISSION_RUN": 2,
		"QUERY_SCOPE_GLOBAL":      3,
	}
)

func (x QueryScope) Enum() *QueryScope {
	p := new(QueryScope)
	*p = x
	return p
}

func (x QueryScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryScope) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_graphrag_proto_enumTypes[0].Descriptor()
}

func (QueryScope) Type() protoreflect.EnumType {
	return &file_api_proto_graphrag_proto_enumTypes[0]
}

func (x QueryScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryScope.Descriptor instead.
func (QueryScope) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{0}
}

// GraphQuery represents a query against the knowledge graph using proto-canonical types.
type GraphQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	NodeTypes     []string               `protobuf:"bytes,4,rep,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`
	MinScore      float64                `protobuf:"fixed64,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MaxScore      float64                `protobuf:"fixed64,6,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	MissionId     string                 `protobuf:"bytes,7,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionRunId  string                 `protobuf:"bytes,8,opt,name=mission_run_id,json=missionRunId,proto3" json:"mission_run_id,omitempty"`
	Scope         QueryScope             `protobuf:"varint,9,opt,name=scope,proto3,enum=gibson.graphrag.QueryScope" json:"scope,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,10,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VectorWeight  float64                `protobuf:"fixed64,11,opt,name=vector_weight,json=vectorWeight,proto3" json:"vector_weight,omitempty"`
	GraphWeight   float64                `protobuf:"fixed64,12,opt,name=graph_weight,json=graphWeight,proto3" json:"graph_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphQuery) Reset() {
	*x = GraphQuery{}
	mi := &file_api_proto_graphrag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphQuery) ProtoMessage() {}

func (x *GraphQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphQuery.ProtoReflect.Descriptor instead.
func (*GraphQuery) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{0}
}

func (x *GraphQuery) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GraphQuery) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *GraphQuery) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *GraphQuery) GetNodeTypes() []string {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

func (x *GraphQuery) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *GraphQuery) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *GraphQuery) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *GraphQuery) GetMissionRunId() string {
	if x != nil {
		return x.MissionRunId
	}
	return ""
}

func (x *GraphQuery) GetScope() QueryScope {
	if x != nil {
		return x.Scope
	}
	return QueryScope_QUERY_SCOPE_UNSPECIFIED
}

func (x *GraphQuery) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GraphQuery) GetVectorWeight() float64 {
	if x != nil {
		return x.VectorWeight
	}
	return 0
}

func (x *GraphQuery) GetGraphWeight() float64 {
	if x != nil {
		return x.GraphWeight
	}
	return 0
}

// QueryResult represents a single result from a graph query.
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *GraphNode             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	VectorScore   float64                `protobuf:"fixed64,3,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"`
	GraphScore    float64                `protobuf:"fixed64,4,opt,name=graph_score,json=graphScore,proto3" json:"graph_score,omitempty"`
	Path          []string               `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	Distance      int32                  `protobuf:"varint,6,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_api_proto_graphrag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResult) GetNode() *GraphNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *QueryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryResult) GetVectorScore() float64 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *QueryResult) GetGraphScore() float64 {
	if x != nil {
		return x.GraphScore
	}
	return 0
}

func (x *QueryResult) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *QueryResult) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// GraphNode represents a node in the knowledge graph.
// This is the proto-canonical representation for storage and query operations.
type GraphNode struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type       string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Node type (e.g., "host", "port", "finding")
	Properties map[string]*Value      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Content for semantic search (optional)
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Scoping fields (injected by harness)
	MissionId    string `protobuf:"bytes,10,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionRunId string `protobuf:"bytes,11,opt,name=mission_run_id,json=missionRunId,proto3" json:"mission_run_id,omitempty"`
	AgentRunId   string `protobuf:"bytes,12,opt,name=agent_run_id,json=agentRunId,proto3" json:"agent_run_id,omitempty"`
	DiscoveredBy string `protobuf:"bytes,13,opt,name=discovered_by,json=discoveredBy,proto3" json:"discovered_by,omitempty"`
	DiscoveredAt int64  `protobuf:"varint,14,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	// Timestamps
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Parent reference
	ParentId           *string `protobuf:"bytes,30,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentType         *string `protobuf:"bytes,31,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"`
	ParentRelationship *string `protobuf:"bytes,32,opt,name=parent_relationship,json=parentRelationship,proto3,oneof" json:"parent_relationship,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_api_proto_graphrag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{2}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GraphNode) GetProperties() map[string]*Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphNode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GraphNode) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *GraphNode) GetMissionRunId() string {
	if x != nil {
		return x.MissionRunId
	}
	return ""
}

func (x *GraphNode) GetAgentRunId() string {
	if x != nil {
		return x.AgentRunId
	}
	return ""
}

func (x *GraphNode) GetDiscoveredBy() string {
	if x != nil {
		return x.DiscoveredBy
	}
	return ""
}

func (x *GraphNode) GetDiscoveredAt() int64 {
	if x != nil {
		return x.DiscoveredAt
	}
	return 0
}

func (x *GraphNode) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GraphNode) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GraphNode) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *GraphNode) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

func (x *GraphNode) GetParentRelationship() string {
	if x != nil && x.ParentRelationship != nil {
		return *x.ParentRelationship
	}
	return ""
}

// Value represents a dynamic property value.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	//	*Value_ListValue
	//	*Value_MapValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_proto_graphrag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,8,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_MapValue) isValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_proto_graphrag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{4}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_api_proto_graphrag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{5}
}

func (x *MapValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Relationship represents a connection between two nodes.
type Relationship struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId     string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId       string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Type       string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Properties map[string]*Value      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight     float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// Scoping
	MissionId    string `protobuf:"bytes,10,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionRunId string `protobuf:"bytes,11,opt,name=mission_run_id,json=missionRunId,proto3" json:"mission_run_id,omitempty"`
	// Timestamps
	CreatedAt     int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_api_proto_graphrag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{6}
}

func (x *Relationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relationship) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Relationship) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Relationship) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relationship) GetProperties() map[string]*Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Relationship) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Relationship) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *Relationship) GetMissionRunId() string {
	if x != nil {
		return x.MissionRunId
	}
	return ""
}

func (x *Relationship) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// DiscoveryResult is a standardized container for tool-discovered entities.
// Tools populate this message and Gibson automatically persists to the graph.
type DiscoveryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset discoveries
	Hosts        []*Host        `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Ports        []*Port        `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Services     []*Service     `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Endpoints    []*Endpoint    `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Domains      []*Domain      `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"`
	Subdomains   []*Subdomain   `protobuf:"bytes,6,rep,name=subdomains,proto3" json:"subdomains,omitempty"`
	Technologies []*Technology  `protobuf:"bytes,7,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Certificates []*Certificate `protobuf:"bytes,8,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// Security findings
	Findings []*Finding  `protobuf:"bytes,9,rep,name=findings,proto3" json:"findings,omitempty"`
	Evidence []*Evidence `protobuf:"bytes,10,rep,name=evidence,proto3" json:"evidence,omitempty"`
	// Custom extensions
	CustomNodes           []*CustomNode           `protobuf:"bytes,20,rep,name=custom_nodes,json=customNodes,proto3" json:"custom_nodes,omitempty"`
	ExplicitRelationships []*ExplicitRelationship `protobuf:"bytes,21,rep,name=explicit_relationships,json=explicitRelationships,proto3" json:"explicit_relationships,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DiscoveryResult) Reset() {
	*x = DiscoveryResult{}
	mi := &file_api_proto_graphrag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResult) ProtoMessage() {}

func (x *DiscoveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResult.ProtoReflect.Descriptor instead.
func (*DiscoveryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoveryResult) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *DiscoveryResult) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DiscoveryResult) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DiscoveryResult) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *DiscoveryResult) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DiscoveryResult) GetSubdomains() []*Subdomain {
	if x != nil {
		return x.Subdomains
	}
	return nil
}

func (x *DiscoveryResult) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *DiscoveryResult) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *DiscoveryResult) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *DiscoveryResult) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DiscoveryResult) GetCustomNodes() []*CustomNode {
	if x != nil {
		return x.CustomNodes
	}
	return nil
}

func (x *DiscoveryResult) GetExplicitRelationships() []*ExplicitRelationship {
	if x != nil {
		return x.ExplicitRelationships
	}
	return nil
}

// Host discovered by a tool.
type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // Agent-generated UUID for this host
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname      *string                `protobuf:"bytes,3,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	State         *string                `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Os            *string                `protobuf:"bytes,5,opt,name=os,proto3,oneof" json:"os,omitempty"`
	OsVersion     *string                `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3,oneof" json:"os_version,omitempty"`
	MacAddress    *string                `protobuf:"bytes,7,opt,name=mac_address,json=macAddress,proto3,oneof" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_api_proto_graphrag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{8}
}

func (x *Host) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Host) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *Host) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Host) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *Host) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

func (x *Host) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

// Port discovered on a host.
type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                 // Agent-generated UUID for this port
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // Parent Host UUID
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	State         *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Reason        *string                `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_api_proto_graphrag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{9}
}

func (x *Port) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Port) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Port) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Port) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// Service running on a port.
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                 // Agent-generated UUID for this service
	PortId        string                 `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"` // Parent Port UUID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Product       *string                `protobuf:"bytes,4,opt,name=product,proto3,oneof" json:"product,omitempty"`
	Version       *string                `protobuf:"bytes,5,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ExtraInfo     *string                `protobuf:"bytes,6,opt,name=extra_info,json=extraInfo,proto3,oneof" json:"extra_info,omitempty"`
	Banner        *string                `protobuf:"bytes,7,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	Cpe           *string                `protobuf:"bytes,8,opt,name=cpe,proto3,oneof" json:"cpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_proto_graphrag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Service) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Service) GetExtraInfo() string {
	if x != nil && x.ExtraInfo != nil {
		return *x.ExtraInfo
	}
	return ""
}

func (x *Service) GetBanner() string {
	if x != nil && x.Banner != nil {
		return *x.Banner
	}
	return ""
}

func (x *Service) GetCpe() string {
	if x != nil && x.Cpe != nil {
		return *x.Cpe
	}
	return ""
}

// Endpoint (URL) on a service.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                          // Agent-generated UUID for this endpoint
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // Parent Service UUID
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Method        *string                `protobuf:"bytes,4,opt,name=method,proto3,oneof" json:"method,omitempty"`
	StatusCode    *int32                 `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3,oneof" json:"status_code,omitempty"`
	ContentType   *string                `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	ContentLength *int64                 `protobuf:"varint,7,opt,name=content_length,json=contentLength,proto3,oneof" json:"content_length,omitempty"`
	Title         *string                `protobuf:"bytes,8,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_proto_graphrag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{11}
}

func (x *Endpoint) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Endpoint) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Endpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Endpoint) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *Endpoint) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *Endpoint) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *Endpoint) GetContentLength() int64 {
	if x != nil && x.ContentLength != nil {
		return *x.ContentLength
	}
	return 0
}

func (x *Endpoint) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

// Domain discovered.
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // Agent-generated UUID for this domain
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Registrar     *string                `protobuf:"bytes,3,opt,name=registrar,proto3,oneof" json:"registrar,omitempty"`
	CreatedDate   *int64                 `protobuf:"varint,4,opt,name=created_date,json=createdDate,proto3,oneof" json:"created_date,omitempty"`
	ExpiryDate    *int64                 `protobuf:"varint,5,opt,name=expiry_date,json=expiryDate,proto3,oneof" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_api_proto_graphrag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{12}
}

func (x *Domain) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetRegistrar() string {
	if x != nil && x.Registrar != nil {
		return *x.Registrar
	}
	return ""
}

func (x *Domain) GetCreatedDate() int64 {
	if x != nil && x.CreatedDate != nil {
		return *x.CreatedDate
	}
	return 0
}

func (x *Domain) GetExpiryDate() int64 {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return 0
}

// Subdomain under a domain.
type Subdomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                       // Agent-generated UUID for this subdomain
	DomainId      string                 `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"` // Parent Domain UUID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subdomain) Reset() {
	*x = Subdomain{}
	mi := &file_api_proto_graphrag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subdomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subdomain) ProtoMessage() {}

func (x *Subdomain) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subdomain.ProtoReflect.Descriptor instead.
func (*Subdomain) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{13}
}

func (x *Subdomain) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Subdomain) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Subdomain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subdomain) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

// Technology detected.
type Technology struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // Agent-generated UUID for this technology
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version    *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Category   *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Confidence *int32                 `protobuf:"varint,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Cpe        *string                `protobuf:"bytes,6,opt,name=cpe,proto3,oneof" json:"cpe,omitempty"`
	// Parent entity reference (optional - tech can be associated with various entities)
	ParentId      *string `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentType    *string `protobuf:"bytes,11,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"` // e.g., "service", "endpoint", "host"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Technology) Reset() {
	*x = Technology{}
	mi := &file_api_proto_graphrag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technology) ProtoMessage() {}

func (x *Technology) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technology.ProtoReflect.Descriptor instead.
func (*Technology) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{14}
}

func (x *Technology) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Technology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technology) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Technology) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Technology) GetConfidence() int32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Technology) GetCpe() string {
	if x != nil && x.Cpe != nil {
		return *x.Cpe
	}
	return ""
}

func (x *Technology) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Technology) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

// Certificate discovered.
type Certificate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // Agent-generated UUID for this certificate
	Subject           *string                `protobuf:"bytes,2,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Issuer            *string                `protobuf:"bytes,3,opt,name=issuer,proto3,oneof" json:"issuer,omitempty"`
	SerialNumber      *string                `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	NotBefore         *int64                 `protobuf:"varint,5,opt,name=not_before,json=notBefore,proto3,oneof" json:"not_before,omitempty"`
	NotAfter          *int64                 `protobuf:"varint,6,opt,name=not_after,json=notAfter,proto3,oneof" json:"not_after,omitempty"`
	FingerprintSha256 *string                `protobuf:"bytes,7,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3,oneof" json:"fingerprint_sha256,omitempty"`
	San               *string                `protobuf:"bytes,8,opt,name=san,proto3,oneof" json:"san,omitempty"`
	// Parent entity reference (optional - cert can be associated with various entities)
	ParentId      *string `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentType    *string `protobuf:"bytes,11,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"` // e.g., "service", "endpoint", "host"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_api_proto_graphrag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{15}
}

func (x *Certificate) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Certificate) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Certificate) GetIssuer() string {
	if x != nil && x.Issuer != nil {
		return *x.Issuer
	}
	return ""
}

func (x *Certificate) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *Certificate) GetNotBefore() int64 {
	if x != nil && x.NotBefore != nil {
		return *x.NotBefore
	}
	return 0
}

func (x *Certificate) GetNotAfter() int64 {
	if x != nil && x.NotAfter != nil {
		return *x.NotAfter
	}
	return 0
}

func (x *Certificate) GetFingerprintSha256() string {
	if x != nil && x.FingerprintSha256 != nil {
		return *x.FingerprintSha256
	}
	return ""
}

func (x *Certificate) GetSan() string {
	if x != nil && x.San != nil {
		return *x.San
	}
	return ""
}

func (x *Certificate) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Certificate) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

// Finding (vulnerability or security issue).
type Finding struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // Agent-generated UUID for this finding
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Severity    string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence  *float64               `protobuf:"fixed64,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Category    *string                `protobuf:"bytes,6,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Remediation *string                `protobuf:"bytes,7,opt,name=remediation,proto3,oneof" json:"remediation,omitempty"`
	CvssScore   *float64               `protobuf:"fixed64,8,opt,name=cvss_score,json=cvssScore,proto3,oneof" json:"cvss_score,omitempty"`
	CveIds      *string                `protobuf:"bytes,9,opt,name=cve_ids,json=cveIds,proto3,oneof" json:"cve_ids,omitempty"`
	// Parent entity reference (optional - finding can be associated with various entities)
	ParentId      *string `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentType    *string `protobuf:"bytes,11,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"` // e.g., "service", "endpoint", "host", "technology"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_api_proto_graphrag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{16}
}

func (x *Finding) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Finding) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil && x.Remediation != nil {
		return *x.Remediation
	}
	return ""
}

func (x *Finding) GetCvssScore() float64 {
	if x != nil && x.CvssScore != nil {
		return *x.CvssScore
	}
	return 0
}

func (x *Finding) GetCveIds() string {
	if x != nil && x.CveIds != nil {
		return *x.CveIds
	}
	return ""
}

func (x *Finding) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Finding) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

// Evidence for a finding.
type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                          // Agent-generated UUID for this evidence
	FindingId     string                 `protobuf:"bytes,2,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"` // Parent Finding UUID
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Content       *string                `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Url           *string                `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_api_proto_graphrag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{17}
}

func (x *Evidence) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Evidence) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *Evidence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Evidence) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Evidence) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

// CustomNode for entities not in standard taxonomy.
type CustomNode struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeType         string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	IdProperties     map[string]string      `protobuf:"bytes,2,rep,name=id_properties,json=idProperties,proto3" json:"id_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Properties       map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParentType       *string                `protobuf:"bytes,4,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"`
	ParentId         map[string]string      `protobuf:"bytes,5,rep,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RelationshipType *string                `protobuf:"bytes,6,opt,name=relationship_type,json=relationshipType,proto3,oneof" json:"relationship_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomNode) Reset() {
	*x = CustomNode{}
	mi := &file_api_proto_graphrag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomNode) ProtoMessage() {}

func (x *CustomNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomNode.ProtoReflect.Descriptor instead.
func (*CustomNode) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{18}
}

func (x *CustomNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *CustomNode) GetIdProperties() map[string]string {
	if x != nil {
		return x.IdProperties
	}
	return nil
}

func (x *CustomNode) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *CustomNode) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

func (x *CustomNode) GetParentId() map[string]string {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *CustomNode) GetRelationshipType() string {
	if x != nil && x.RelationshipType != nil {
		return *x.RelationshipType
	}
	return ""
}

// ExplicitRelationship for custom connections.
type ExplicitRelationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromType         string                 `protobuf:"bytes,1,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	FromId           map[string]string      `protobuf:"bytes,2,rep,name=from_id,json=fromId,proto3" json:"from_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ToType           string                 `protobuf:"bytes,3,opt,name=to_type,json=toType,proto3" json:"to_type,omitempty"`
	ToId             map[string]string      `protobuf:"bytes,4,rep,name=to_id,json=toId,proto3" json:"to_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RelationshipType string                 `protobuf:"bytes,5,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExplicitRelationship) Reset() {
	*x = ExplicitRelationship{}
	mi := &file_api_proto_graphrag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitRelationship) ProtoMessage() {}

func (x *ExplicitRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_graphrag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitRelationship.ProtoReflect.Descriptor instead.
func (*ExplicitRelationship) Descriptor() ([]byte, []int) {
	return file_api_proto_graphrag_proto_rawDescGZIP(), []int{19}
}

func (x *ExplicitRelationship) GetFromType() string {
	if x != nil {
		return x.FromType
	}
	return ""
}

func (x *ExplicitRelationship) GetFromId() map[string]string {
	if x != nil {
		return x.FromId
	}
	return nil
}

func (x *ExplicitRelationship) GetToType() string {
	if x != nil {
		return x.ToType
	}
	return ""
}

func (x *ExplicitRelationship) GetToId() map[string]string {
	if x != nil {
		return x.ToId
	}
	return nil
}

func (x *ExplicitRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *ExplicitRelationship) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_api_proto_graphrag_proto protoreflect.FileDescriptor

const file_api_proto_graphrag_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/graphrag.proto\x12\x0fgibson.graphrag\"\xec\x03\n" +
	"\n" +
	"GraphQuery\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x1d\n" +
	"\n" +
	"node_types\x18\x04 \x03(\tR\tnodeTypes\x12\x1b\n" +
	"\tmin_score\x18\x05 \x01(\x01R\bminScore\x12\x1b\n" +
	"\tmax_score\x18\x06 \x01(\x01R\bmaxScore\x12\x1d\n" +
	"\n" +
	"mission_id\x18\a \x01(\tR\tmissionId\x12$\n" +
	"\x0emission_run_id\x18\b \x01(\tR\fmissionRunId\x121\n" +
	"\x05scope\x18\t \x01(\x0e2\x1b.gibson.graphrag.QueryScopeR\x05scope\x12B\n" +
	"\afilters\x18\n" +
	" \x03(\v2(.gibson.graphrag.GraphQuery.FiltersEntryR\afilters\x12#\n" +
	"\rvector_weight\x18\v \x01(\x01R\fvectorWeight\x12!\n" +
	"\fgraph_weight\x18\f \x01(\x01R\vgraphWeight\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\vQueryResult\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.gibson.graphrag.GraphNodeR\x04node\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12!\n" +
	"\fvector_score\x18\x03 \x01(\x01R\vvectorScore\x12\x1f\n" +
	"\vgraph_score\x18\x04 \x01(\x01R\n" +
	"graphScore\x12\x12\n" +
	"\x04path\x18\x05 \x03(\tR\x04path\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x05R\bdistance\"\x8f\x05\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12J\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2*.gibson.graphrag.GraphNode.PropertiesEntryR\n" +
	"properties\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"mission_id\x18\n" +
	" \x01(\tR\tmissionId\x12$\n" +
	"\x0emission_run_id\x18\v \x01(\tR\fmissionRunId\x12 \n" +
	"\fagent_run_id\x18\f \x01(\tR\n" +
	"agentRunId\x12#\n" +
	"\rdiscovered_by\x18\r \x01(\tR\fdiscoveredBy\x12#\n" +
	"\rdiscovered_at\x18\x0e \x01(\x03R\fdiscoveredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12 \n" +
	"\tparent_id\x18\x1e \x01(\tH\x00R\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_type\x18\x1f \x01(\tH\x01R\n" +
	"parentType\x88\x01\x01\x124\n" +
	"\x13parent_relationship\x18  \x01(\tH\x02R\x12parentRelationship\x88\x01\x01\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gibson.graphrag.ValueR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_typeB\x16\n" +
	"\x14_parent_relationship\"\xde\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12)\n" +
	"\x0ftimestamp_value\x18\x06 \x01(\x03H\x00R\x0etimestampValue\x12;\n" +
	"\n" +
	"list_value\x18\a \x01(\v2\x1a.gibson.graphrag.ListValueH\x00R\tlistValue\x128\n" +
	"\tmap_value\x18\b \x01(\v2\x19.gibson.graphrag.MapValueH\x00R\bmapValueB\x06\n" +
	"\x04kind\";\n" +
	"\tListValue\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.gibson.graphrag.ValueR\x06values\"\x9c\x01\n" +
	"\bMapValue\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.gibson.graphrag.MapValue.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gibson.graphrag.ValueR\x05value:\x028\x01\"\x82\x03\n" +
	"\fRelationship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12M\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2-.gibson.graphrag.Relationship.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1d\n" +
	"\n" +
	"mission_id\x18\n" +
	" \x01(\tR\tmissionId\x12$\n" +
	"\x0emission_run_id\x18\v \x01(\tR\fmissionRunId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gibson.graphrag.ValueR\x05value:\x028\x01\"\xd7\x05\n" +
	"\x0fDiscoveryResult\x12+\n" +
	"\x05hosts\x18\x01 \x03(\v2\x15.gibson.graphrag.HostR\x05hosts\x12+\n" +
	"\x05ports\x18\x02 \x03(\v2\x15.gibson.graphrag.PortR\x05ports\x124\n" +
	"\bservices\x18\x03 \x03(\v2\x18.gibson.graphrag.ServiceR\bservices\x127\n" +
	"\tendpoints\x18\x04 \x03(\v2\x19.gibson.graphrag.EndpointR\tendpoints\x121\n" +
	"\adomains\x18\x05 \x03(\v2\x17.gibson.graphrag.DomainR\adomains\x12:\n" +
	"\n" +
	"subdomains\x18\x06 \x03(\v2\x1a.gibson.graphrag.SubdomainR\n" +
	"subdomains\x12?\n" +
	"\ftechnologies\x18\a \x03(\v2\x1b.gibson.graphrag.TechnologyR\ftechnologies\x12@\n" +
	"\fcertificates\x18\b \x03(\v2\x1c.gibson.graphrag.CertificateR\fcertificates\x124\n" +
	"\bfindings\x18\t \x03(\v2\x18.gibson.graphrag.FindingR\bfindings\x125\n" +
	"\bevidence\x18\n" +
	" \x03(\v2\x19.gibson.graphrag.EvidenceR\bevidence\x12>\n" +
	"\fcustom_nodes\x18\x14 \x03(\v2\x1b.gibson.graphrag.CustomNodeR\vcustomNodes\x12\\\n" +
	"\x16explicit_relationships\x18\x15 \x03(\v2%.gibson.graphrag.ExplicitRelationshipR\x15explicitRelationships\"\x8a\x02\n" +
	"\x04Host\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1f\n" +
	"\bhostname\x18\x03 \x01(\tH\x01R\bhostname\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x02R\x05state\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x05 \x01(\tH\x03R\x02os\x88\x01\x01\x12\"\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tH\x04R\tosVersion\x88\x01\x01\x12$\n" +
	"\vmac_address\x18\a \x01(\tH\x05R\n" +
	"macAddress\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_hostnameB\b\n" +
	"\x06_stateB\x05\n" +
	"\x03_osB\r\n" +
	"\v_os_versionB\x0e\n" +
	"\f_mac_address\"\xbc\x01\n" +
	"\x04Port\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x01R\x05state\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\tH\x02R\x06reason\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_stateB\t\n" +
	"\a_reason\"\xa2\x02\n" +
	"\aService\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\aproduct\x18\x04 \x01(\tH\x01R\aproduct\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\tH\x02R\aversion\x88\x01\x01\x12\"\n" +
	"\n" +
	"extra_info\x18\x06 \x01(\tH\x03R\textraInfo\x88\x01\x01\x12\x1b\n" +
	"\x06banner\x18\a \x01(\tH\x04R\x06banner\x88\x01\x01\x12\x15\n" +
	"\x03cpe\x18\b \x01(\tH\x05R\x03cpe\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_productB\n" +
	"\n" +
	"\b_versionB\r\n" +
	"\v_extra_infoB\t\n" +
	"\a_bannerB\x06\n" +
	"\x04_cpe\"\xd2\x02\n" +
	"\bEndpoint\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\x06method\x18\x04 \x01(\tH\x01R\x06method\x88\x01\x01\x12$\n" +
	"\vstatus_code\x18\x05 \x01(\x05H\x02R\n" +
	"statusCode\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x06 \x01(\tH\x03R\vcontentType\x88\x01\x01\x12*\n" +
	"\x0econtent_length\x18\a \x01(\x03H\x04R\rcontentLength\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\b \x01(\tH\x05R\x05title\x88\x01\x01B\x05\n" +
	"\x03_idB\t\n" +
	"\a_methodB\x0e\n" +
	"\f_status_codeB\x0f\n" +
	"\r_content_typeB\x11\n" +
	"\x0f_content_lengthB\b\n" +
	"\x06_title\"\xd8\x01\n" +
	"\x06Domain\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tregistrar\x18\x03 \x01(\tH\x01R\tregistrar\x88\x01\x01\x12&\n" +
	"\fcreated_date\x18\x04 \x01(\x03H\x02R\vcreatedDate\x88\x01\x01\x12$\n" +
	"\vexpiry_date\x18\x05 \x01(\x03H\x03R\n" +
	"expiryDate\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_registrarB\x0f\n" +
	"\r_created_dateB\x0e\n" +
	"\f_expiry_date\"\x88\x01\n" +
	"\tSubdomain\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\tR\bdomainId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\tfull_name\x18\x04 \x01(\tH\x01R\bfullName\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_full_name\"\xce\x02\n" +
	"\n" +
	"Technology\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x02R\bcategory\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x05H\x03R\n" +
	"confidence\x88\x01\x01\x12\x15\n" +
	"\x03cpe\x18\x06 \x01(\tH\x04R\x03cpe\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\n" +
	" \x01(\tH\x05R\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_type\x18\v \x01(\tH\x06R\n" +
	"parentType\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_versionB\v\n" +
	"\t_categoryB\r\n" +
	"\v_confidenceB\x06\n" +
	"\x04_cpeB\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_type\"\xeb\x03\n" +
	"\vCertificate\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\x02 \x01(\tH\x01R\asubject\x88\x01\x01\x12\x1b\n" +
	"\x06issuer\x18\x03 \x01(\tH\x02R\x06issuer\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x04 \x01(\tH\x03R\fserialNumber\x88\x01\x01\x12\"\n" +
	"\n" +
	"not_before\x18\x05 \x01(\x03H\x04R\tnotBefore\x88\x01\x01\x12 \n" +
	"\tnot_after\x18\x06 \x01(\x03H\x05R\bnotAfter\x88\x01\x01\x122\n" +
	"\x12fingerprint_sha256\x18\a \x01(\tH\x06R\x11fingerprintSha256\x88\x01\x01\x12\x15\n" +
	"\x03san\x18\b \x01(\tH\aR\x03san\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\n" +
	" \x01(\tH\bR\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_type\x18\v \x01(\tH\tR\n" +
	"parentType\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_subjectB\t\n" +
	"\a_issuerB\x10\n" +
	"\x0e_serial_numberB\r\n" +
	"\v_not_beforeB\f\n" +
	"\n" +
	"_not_afterB\x15\n" +
	"\x13_fingerprint_sha256B\x06\n" +
	"\x04_sanB\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_type\"\xea\x03\n" +
	"\aFinding\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01H\x02R\n" +
	"confidence\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x06 \x01(\tH\x03R\bcategory\x88\x01\x01\x12%\n" +
	"\vremediation\x18\a \x01(\tH\x04R\vremediation\x88\x01\x01\x12\"\n" +
	"\n" +
	"cvss_score\x18\b \x01(\x01H\x05R\tcvssScore\x88\x01\x01\x12\x1c\n" +
	"\acve_ids\x18\t \x01(\tH\x06R\x06cveIds\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\n" +
	" \x01(\tH\aR\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_type\x18\v \x01(\tH\bR\n" +
	"parentType\x88\x01\x01B\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_confidenceB\v\n" +
	"\t_categoryB\x0e\n" +
	"\f_remediationB\r\n" +
	"\v_cvss_scoreB\n" +
	"\n" +
	"\b_cve_idsB\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_type\"\xa3\x01\n" +
	"\bEvidence\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x02 \x01(\tR\tfindingId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\acontent\x18\x04 \x01(\tH\x01R\acontent\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x02R\x03url\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_contentB\x06\n" +
	"\x04_url\"\xcd\x04\n" +
	"\n" +
	"CustomNode\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12R\n" +
	"\rid_properties\x18\x02 \x03(\v2-.gibson.graphrag.CustomNode.IdPropertiesEntryR\fidProperties\x12K\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2+.gibson.graphrag.CustomNode.PropertiesEntryR\n" +
	"properties\x12$\n" +
	"\vparent_type\x18\x04 \x01(\tH\x00R\n" +
	"parentType\x88\x01\x01\x12F\n" +
	"\tparent_id\x18\x05 \x03(\v2).gibson.graphrag.CustomNode.ParentIdEntryR\bparentId\x120\n" +
	"\x11relationship_type\x18\x06 \x01(\tH\x01R\x10relationshipType\x88\x01\x01\x1a?\n" +
	"\x11IdPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rParentIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_parent_typeB\x14\n" +
	"\x12_relationship_type\"\x95\x04\n" +
	"\x14ExplicitRelationship\x12\x1b\n" +
	"\tfrom_type\x18\x01 \x01(\tR\bfromType\x12J\n" +
	"\afrom_id\x18\x02 \x03(\v21.gibson.graphrag.ExplicitRelationship.FromIdEntryR\x06fromId\x12\x17\n" +
	"\ato_type\x18\x03 \x01(\tR\x06toType\x12D\n" +
	"\x05to_id\x18\x04 \x03(\v2/.gibson.graphrag.ExplicitRelationship.ToIdEntryR\x04toId\x12+\n" +
	"\x11relationship_type\x18\x05 \x01(\tR\x10relationshipType\x12U\n" +
	"\n" +
	"properties\x18\x06 \x03(\v25.gibson.graphrag.ExplicitRelationship.PropertiesEntryR\n" +
	"properties\x1a9\n" +
	"\vFromIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tToIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*w\n" +
	"\n" +
	"QueryScope\x12\x1b\n" +
	"\x17QUERY_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13QUERY_SCOPE_MISSION\x10\x01\x12\x1b\n" +
	"\x17QUERY_SCOPE_MISSION_RUN\x10\x02\x12\x16\n" +
	"\x12QUERY_SCOPE_GLOBAL\x10\x03B/Z-github.com/zero-day-ai/sdk/api/gen/graphragpbb\x06proto3"

var (
	file_api_proto_graphrag_proto_rawDescOnce sync.Once
	file_api_proto_graphrag_proto_rawDescData []byte
)

func file_api_proto_graphrag_proto_rawDescGZIP() []byte {
	file_api_proto_graphrag_proto_rawDescOnce.Do(func() {
		file_api_proto_graphrag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_graphrag_proto_rawDesc), len(file_api_proto_graphrag_proto_rawDesc)))
	})
	return file_api_proto_graphrag_proto_rawDescData
}

var file_api_proto_graphrag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_graphrag_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_proto_graphrag_proto_goTypes = []any{
	(QueryScope)(0),              // 0: gibson.graphrag.QueryScope
	(*GraphQuery)(nil),           // 1: gibson.graphrag.GraphQuery
	(*QueryResult)(nil),          // 2: gibson.graphrag.QueryResult
	(*GraphNode)(nil),            // 3: gibson.graphrag.GraphNode
	(*Value)(nil),                // 4: gibson.graphrag.Value
	(*ListValue)(nil),            // 5: gibson.graphrag.ListValue
	(*MapValue)(nil),             // 6: gibson.graphrag.MapValue
	(*Relationship)(nil),         // 7: gibson.graphrag.Relationship
	(*DiscoveryResult)(nil),      // 8: gibson.graphrag.DiscoveryResult
	(*Host)(nil),                 // 9: gibson.graphrag.Host
	(*Port)(nil),                 // 10: gibson.graphrag.Port
	(*Service)(nil),              // 11: gibson.graphrag.Service
	(*Endpoint)(nil),             // 12: gibson.graphrag.Endpoint
	(*Domain)(nil),               // 13: gibson.graphrag.Domain
	(*Subdomain)(nil),            // 14: gibson.graphrag.Subdomain
	(*Technology)(nil),           // 15: gibson.graphrag.Technology
	(*Certificate)(nil),          // 16: gibson.graphrag.Certificate
	(*Finding)(nil),              // 17: gibson.graphrag.Finding
	(*Evidence)(nil),             // 18: gibson.graphrag.Evidence
	(*CustomNode)(nil),           // 19: gibson.graphrag.CustomNode
	(*ExplicitRelationship)(nil), // 20: gibson.graphrag.ExplicitRelationship
	nil,                          // 21: gibson.graphrag.GraphQuery.FiltersEntry
	nil,                          // 22: gibson.graphrag.GraphNode.PropertiesEntry
	nil,                          // 23: gibson.graphrag.MapValue.FieldsEntry
	nil,                          // 24: gibson.graphrag.Relationship.PropertiesEntry
	nil,                          // 25: gibson.graphrag.CustomNode.IdPropertiesEntry
	nil,                          // 26: gibson.graphrag.CustomNode.PropertiesEntry
	nil,                          // 27: gibson.graphrag.CustomNode.ParentIdEntry
	nil,                          // 28: gibson.graphrag.ExplicitRelationship.FromIdEntry
	nil,                          // 29: gibson.graphrag.ExplicitRelationship.ToIdEntry
	nil,                          // 30: gibson.graphrag.ExplicitRelationship.PropertiesEntry
}
var file_api_proto_graphrag_proto_depIdxs = []int32{
	0,  // 0: gibson.graphrag.GraphQuery.scope:type_name -> gibson.graphrag.QueryScope
	21, // 1: gibson.graphrag.GraphQuery.filters:type_name -> gibson.graphrag.GraphQuery.FiltersEntry
	3,  // 2: gibson.graphrag.QueryResult.node:type_name -> gibson.graphrag.GraphNode
	22, // 3: gibson.graphrag.GraphNode.properties:type_name -> gibson.graphrag.GraphNode.PropertiesEntry
	5,  // 4: gibson.graphrag.Value.list_value:type_name -> gibson.graphrag.ListValue
	6,  // 5: gibson.graphrag.Value.map_value:type_name -> gibson.graphrag.MapValue
	4,  // 6: gibson.graphrag.ListValue.values:type_name -> gibson.graphrag.Value
	23, // 7: gibson.graphrag.MapValue.fields:type_name -> gibson.graphrag.MapValue.FieldsEntry
	24, // 8: gibson.graphrag.Relationship.properties:type_name -> gibson.graphrag.Relationship.PropertiesEntry
	9,  // 9: gibson.graphrag.DiscoveryResult.hosts:type_name -> gibson.graphrag.Host
	10, // 10: gibson.graphrag.DiscoveryResult.ports:type_name -> gibson.graphrag.Port
	11, // 11: gibson.graphrag.DiscoveryResult.services:type_name -> gibson.graphrag.Service
	12, // 12: gibson.graphrag.DiscoveryResult.endpoints:type_name -> gibson.graphrag.Endpoint
	13, // 13: gibson.graphrag.DiscoveryResult.domains:type_name -> gibson.graphrag.Domain
	14, // 14: gibson.graphrag.DiscoveryResult.subdomains:type_name -> gibson.graphrag.Subdomain
	15, // 15: gibson.graphrag.DiscoveryResult.technologies:type_name -> gibson.graphrag.Technology
	16, // 16: gibson.graphrag.DiscoveryResult.certificates:type_name -> gibson.graphrag.Certificate
	17, // 17: gibson.graphrag.DiscoveryResult.findings:type_name -> gibson.graphrag.Finding
	18, // 18: gibson.graphrag.DiscoveryResult.evidence:type_name -> gibson.graphrag.Evidence
	19, // 19: gibson.graphrag.DiscoveryResult.custom_nodes:type_name -> gibson.graphrag.CustomNode
	20, // 20: gibson.graphrag.DiscoveryResult.explicit_relationships:type_name -> gibson.graphrag.ExplicitRelationship
	25, // 21: gibson.graphrag.CustomNode.id_properties:type_name -> gibson.graphrag.CustomNode.IdPropertiesEntry
	26, // 22: gibson.graphrag.CustomNode.properties:type_name -> gibson.graphrag.CustomNode.PropertiesEntry
	27, // 23: gibson.graphrag.CustomNode.parent_id:type_name -> gibson.graphrag.CustomNode.ParentIdEntry
	28, // 24: gibson.graphrag.ExplicitRelationship.from_id:type_name -> gibson.graphrag.ExplicitRelationship.FromIdEntry
	29, // 25: gibson.graphrag.ExplicitRelationship.to_id:type_name -> gibson.graphrag.ExplicitRelationship.ToIdEntry
	30, // 26: gibson.graphrag.ExplicitRelationship.properties:type_name -> gibson.graphrag.ExplicitRelationship.PropertiesEntry
	4,  // 27: gibson.graphrag.GraphNode.PropertiesEntry.value:type_name -> gibson.graphrag.Value
	4,  // 28: gibson.graphrag.MapValue.FieldsEntry.value:type_name -> gibson.graphrag.Value
	4,  // 29: gibson.graphrag.Relationship.PropertiesEntry.value:type_name -> gibson.graphrag.Value
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_api_proto_graphrag_proto_init() }
func file_api_proto_graphrag_proto_init() {
	if File_api_proto_graphrag_proto != nil {
		return
	}
	file_api_proto_graphrag_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
	}
	file_api_proto_graphrag_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_proto_graphrag_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_graphrag_proto_rawDesc), len(file_api_proto_graphrag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_graphrag_proto_goTypes,
		DependencyIndexes: file_api_proto_graphrag_proto_depIdxs,
		EnumInfos:         file_api_proto_graphrag_proto_enumTypes,
		MessageInfos:      file_api_proto_graphrag_proto_msgTypes,
	}.Build()
	File_api_proto_graphrag_proto = out.File
	file_api_proto_graphrag_proto_goTypes = nil
	file_api_proto_graphrag_proto_depIdxs = nil
}
