// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 3.0.0
// Generated at: 2026-01-26T14:25:12Z

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/taxonomy.proto

package taxonomypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoreNodeType enumerates all core (validated) node types.
// Custom types use string directly, not this enum.
type CoreNodeType int32

const (
	CoreNodeType_CORE_NODE_TYPE_UNSPECIFIED    CoreNodeType = 0
	CoreNodeType_CORE_NODE_TYPE_MISSION        CoreNodeType = 1
	CoreNodeType_CORE_NODE_TYPE_MISSION_RUN    CoreNodeType = 2
	CoreNodeType_CORE_NODE_TYPE_AGENT_RUN      CoreNodeType = 3
	CoreNodeType_CORE_NODE_TYPE_TOOL_EXECUTION CoreNodeType = 4
	CoreNodeType_CORE_NODE_TYPE_LLM_CALL       CoreNodeType = 5
	CoreNodeType_CORE_NODE_TYPE_DOMAIN         CoreNodeType = 6
	CoreNodeType_CORE_NODE_TYPE_SUBDOMAIN      CoreNodeType = 7
	CoreNodeType_CORE_NODE_TYPE_HOST           CoreNodeType = 8
	CoreNodeType_CORE_NODE_TYPE_PORT           CoreNodeType = 9
	CoreNodeType_CORE_NODE_TYPE_SERVICE        CoreNodeType = 10
	CoreNodeType_CORE_NODE_TYPE_ENDPOINT       CoreNodeType = 11
	CoreNodeType_CORE_NODE_TYPE_TECHNOLOGY     CoreNodeType = 12
	CoreNodeType_CORE_NODE_TYPE_CERTIFICATE    CoreNodeType = 13
	CoreNodeType_CORE_NODE_TYPE_FINDING        CoreNodeType = 14
	CoreNodeType_CORE_NODE_TYPE_EVIDENCE       CoreNodeType = 15
	CoreNodeType_CORE_NODE_TYPE_TECHNIQUE      CoreNodeType = 16
)

// Enum value maps for CoreNodeType.
var (
	CoreNodeType_name = map[int32]string{
		0:  "CORE_NODE_TYPE_UNSPECIFIED",
		1:  "CORE_NODE_TYPE_MISSION",
		2:  "CORE_NODE_TYPE_MISSION_RUN",
		3:  "CORE_NODE_TYPE_AGENT_RUN",
		4:  "CORE_NODE_TYPE_TOOL_EXECUTION",
		5:  "CORE_NODE_TYPE_LLM_CALL",
		6:  "CORE_NODE_TYPE_DOMAIN",
		7:  "CORE_NODE_TYPE_SUBDOMAIN",
		8:  "CORE_NODE_TYPE_HOST",
		9:  "CORE_NODE_TYPE_PORT",
		10: "CORE_NODE_TYPE_SERVICE",
		11: "CORE_NODE_TYPE_ENDPOINT",
		12: "CORE_NODE_TYPE_TECHNOLOGY",
		13: "CORE_NODE_TYPE_CERTIFICATE",
		14: "CORE_NODE_TYPE_FINDING",
		15: "CORE_NODE_TYPE_EVIDENCE",
		16: "CORE_NODE_TYPE_TECHNIQUE",
	}
	CoreNodeType_value = map[string]int32{
		"CORE_NODE_TYPE_UNSPECIFIED":    0,
		"CORE_NODE_TYPE_MISSION":        1,
		"CORE_NODE_TYPE_MISSION_RUN":    2,
		"CORE_NODE_TYPE_AGENT_RUN":      3,
		"CORE_NODE_TYPE_TOOL_EXECUTION": 4,
		"CORE_NODE_TYPE_LLM_CALL":       5,
		"CORE_NODE_TYPE_DOMAIN":         6,
		"CORE_NODE_TYPE_SUBDOMAIN":      7,
		"CORE_NODE_TYPE_HOST":           8,
		"CORE_NODE_TYPE_PORT":           9,
		"CORE_NODE_TYPE_SERVICE":        10,
		"CORE_NODE_TYPE_ENDPOINT":       11,
		"CORE_NODE_TYPE_TECHNOLOGY":     12,
		"CORE_NODE_TYPE_CERTIFICATE":    13,
		"CORE_NODE_TYPE_FINDING":        14,
		"CORE_NODE_TYPE_EVIDENCE":       15,
		"CORE_NODE_TYPE_TECHNIQUE":      16,
	}
)

func (x CoreNodeType) Enum() *CoreNodeType {
	p := new(CoreNodeType)
	*p = x
	return p
}

func (x CoreNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_taxonomy_proto_enumTypes[0].Descriptor()
}

func (CoreNodeType) Type() protoreflect.EnumType {
	return &file_api_proto_taxonomy_proto_enumTypes[0]
}

func (x CoreNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreNodeType.Descriptor instead.
func (CoreNodeType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{0}
}

// CoreRelationType enumerates all core relationship types.
type CoreRelationType int32

const (
	CoreRelationType_CORE_RELATION_TYPE_UNSPECIFIED         CoreRelationType = 0
	CoreRelationType_CORE_RELATION_TYPE_HAS_RUN             CoreRelationType = 1
	CoreRelationType_CORE_RELATION_TYPE_CONTAINS_AGENT_RUN  CoreRelationType = 2
	CoreRelationType_CORE_RELATION_TYPE_EXECUTED_TOOL       CoreRelationType = 3
	CoreRelationType_CORE_RELATION_TYPE_MADE_CALL           CoreRelationType = 4
	CoreRelationType_CORE_RELATION_TYPE_DELEGATED_TO        CoreRelationType = 5
	CoreRelationType_CORE_RELATION_TYPE_HAS_SUBDOMAIN       CoreRelationType = 6
	CoreRelationType_CORE_RELATION_TYPE_RESOLVES_TO         CoreRelationType = 7
	CoreRelationType_CORE_RELATION_TYPE_HAS_PORT            CoreRelationType = 8
	CoreRelationType_CORE_RELATION_TYPE_RUNS_SERVICE        CoreRelationType = 9
	CoreRelationType_CORE_RELATION_TYPE_HAS_ENDPOINT        CoreRelationType = 10
	CoreRelationType_CORE_RELATION_TYPE_USES_TECHNOLOGY     CoreRelationType = 11
	CoreRelationType_CORE_RELATION_TYPE_SERVES_CERTIFICATE  CoreRelationType = 12
	CoreRelationType_CORE_RELATION_TYPE_D_I_S_C_O_V_E_R_E_D CoreRelationType = 13
	CoreRelationType_CORE_RELATION_TYPE_A_F_F_E_C_T_S       CoreRelationType = 14
	CoreRelationType_CORE_RELATION_TYPE_HAS_EVIDENCE        CoreRelationType = 15
	CoreRelationType_CORE_RELATION_TYPE_USES_TECHNIQUE      CoreRelationType = 16
	CoreRelationType_CORE_RELATION_TYPE_LEADS_TO            CoreRelationType = 17
)

// Enum value maps for CoreRelationType.
var (
	CoreRelationType_name = map[int32]string{
		0:  "CORE_RELATION_TYPE_UNSPECIFIED",
		1:  "CORE_RELATION_TYPE_HAS_RUN",
		2:  "CORE_RELATION_TYPE_CONTAINS_AGENT_RUN",
		3:  "CORE_RELATION_TYPE_EXECUTED_TOOL",
		4:  "CORE_RELATION_TYPE_MADE_CALL",
		5:  "CORE_RELATION_TYPE_DELEGATED_TO",
		6:  "CORE_RELATION_TYPE_HAS_SUBDOMAIN",
		7:  "CORE_RELATION_TYPE_RESOLVES_TO",
		8:  "CORE_RELATION_TYPE_HAS_PORT",
		9:  "CORE_RELATION_TYPE_RUNS_SERVICE",
		10: "CORE_RELATION_TYPE_HAS_ENDPOINT",
		11: "CORE_RELATION_TYPE_USES_TECHNOLOGY",
		12: "CORE_RELATION_TYPE_SERVES_CERTIFICATE",
		13: "CORE_RELATION_TYPE_D_I_S_C_O_V_E_R_E_D",
		14: "CORE_RELATION_TYPE_A_F_F_E_C_T_S",
		15: "CORE_RELATION_TYPE_HAS_EVIDENCE",
		16: "CORE_RELATION_TYPE_USES_TECHNIQUE",
		17: "CORE_RELATION_TYPE_LEADS_TO",
	}
	CoreRelationType_value = map[string]int32{
		"CORE_RELATION_TYPE_UNSPECIFIED":         0,
		"CORE_RELATION_TYPE_HAS_RUN":             1,
		"CORE_RELATION_TYPE_CONTAINS_AGENT_RUN":  2,
		"CORE_RELATION_TYPE_EXECUTED_TOOL":       3,
		"CORE_RELATION_TYPE_MADE_CALL":           4,
		"CORE_RELATION_TYPE_DELEGATED_TO":        5,
		"CORE_RELATION_TYPE_HAS_SUBDOMAIN":       6,
		"CORE_RELATION_TYPE_RESOLVES_TO":         7,
		"CORE_RELATION_TYPE_HAS_PORT":            8,
		"CORE_RELATION_TYPE_RUNS_SERVICE":        9,
		"CORE_RELATION_TYPE_HAS_ENDPOINT":        10,
		"CORE_RELATION_TYPE_USES_TECHNOLOGY":     11,
		"CORE_RELATION_TYPE_SERVES_CERTIFICATE":  12,
		"CORE_RELATION_TYPE_D_I_S_C_O_V_E_R_E_D": 13,
		"CORE_RELATION_TYPE_A_F_F_E_C_T_S":       14,
		"CORE_RELATION_TYPE_HAS_EVIDENCE":        15,
		"CORE_RELATION_TYPE_USES_TECHNIQUE":      16,
		"CORE_RELATION_TYPE_LEADS_TO":            17,
	}
)

func (x CoreRelationType) Enum() *CoreRelationType {
	p := new(CoreRelationType)
	*p = x
	return p
}

func (x CoreRelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreRelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_taxonomy_proto_enumTypes[1].Descriptor()
}

func (CoreRelationType) Type() protoreflect.EnumType {
	return &file_api_proto_taxonomy_proto_enumTypes[1]
}

func (x CoreRelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreRelationType.Descriptor instead.
func (CoreRelationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{1}
}

// Value represents a dynamic property value.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	//	*Value_ListValue
	//	*Value_MapValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,8,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_MapValue) isValue_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{1}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{2}
}

func (x *MapValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// GraphNode is the generic node type that can represent any taxonomy node.
// Use typed messages (Host, Port, etc.) for compile-time safety,
// or GraphNode for dynamic/custom types.
type GraphNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // String to allow custom types
	// Properties (flexible key-value)
	Properties map[string]*Value `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parent reference (set by BelongsTo)
	ParentId           *string `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ParentType         *string `protobuf:"bytes,5,opt,name=parent_type,json=parentType,proto3,oneof" json:"parent_type,omitempty"`
	ParentRelationship *string `protobuf:"bytes,6,opt,name=parent_relationship,json=parentRelationship,proto3,oneof" json:"parent_relationship,omitempty"`
	// Scoping (injected by harness - agents never set these)
	MissionId    string `protobuf:"bytes,10,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionRunId string `protobuf:"bytes,11,opt,name=mission_run_id,json=missionRunId,proto3" json:"mission_run_id,omitempty"`
	AgentRunId   string `protobuf:"bytes,12,opt,name=agent_run_id,json=agentRunId,proto3" json:"agent_run_id,omitempty"`
	DiscoveredBy string `protobuf:"bytes,13,opt,name=discovered_by,json=discoveredBy,proto3" json:"discovered_by,omitempty"`
	DiscoveredAt int64  `protobuf:"varint,14,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	// Timestamps
	CreatedAt     int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{3}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GraphNode) GetProperties() map[string]*Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphNode) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *GraphNode) GetParentType() string {
	if x != nil && x.ParentType != nil {
		return *x.ParentType
	}
	return ""
}

func (x *GraphNode) GetParentRelationship() string {
	if x != nil && x.ParentRelationship != nil {
		return *x.ParentRelationship
	}
	return ""
}

func (x *GraphNode) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *GraphNode) GetMissionRunId() string {
	if x != nil {
		return x.MissionRunId
	}
	return ""
}

func (x *GraphNode) GetAgentRunId() string {
	if x != nil {
		return x.AgentRunId
	}
	return ""
}

func (x *GraphNode) GetDiscoveredBy() string {
	if x != nil {
		return x.DiscoveredBy
	}
	return ""
}

func (x *GraphNode) GetDiscoveredAt() int64 {
	if x != nil {
		return x.DiscoveredAt
	}
	return 0
}

func (x *GraphNode) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GraphNode) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Relationship represents a connection between two nodes.
type Relationship struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId     string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId       string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Type       string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // String to allow custom types
	Properties map[string]*Value      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight     float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// Scoping
	MissionId    string `protobuf:"bytes,10,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	MissionRunId string `protobuf:"bytes,11,opt,name=mission_run_id,json=missionRunId,proto3" json:"mission_run_id,omitempty"`
	// Timestamps
	CreatedAt     int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{4}
}

func (x *Relationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relationship) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Relationship) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Relationship) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relationship) GetProperties() map[string]*Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Relationship) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Relationship) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *Relationship) GetMissionRunId() string {
	if x != nil {
		return x.MissionRunId
	}
	return ""
}

func (x *Relationship) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Mission represents: Top-level security assessment mission
type Mission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        string  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Status        *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Description   *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StartedAt     *int64  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *int64  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{5}
}

func (x *Mission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mission) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mission) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Mission) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Mission) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *Mission) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

// MissionRun represents: Single execution of a mission pipeline
type MissionRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	RunNumber   int32   `protobuf:"varint,2,opt,name=run_number,json=runNumber,proto3" json:"run_number,omitempty"`
	Status      *string `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	StartedAt   *int64  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt *int64  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	// Parent reference
	ParentMissionId string `protobuf:"bytes,6,opt,name=parent_mission_id,json=parentMissionId,proto3" json:"parent_mission_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MissionRun) Reset() {
	*x = MissionRun{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRun) ProtoMessage() {}

func (x *MissionRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionRun.ProtoReflect.Descriptor instead.
func (*MissionRun) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{6}
}

func (x *MissionRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MissionRun) GetRunNumber() int32 {
	if x != nil {
		return x.RunNumber
	}
	return 0
}

func (x *MissionRun) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *MissionRun) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *MissionRun) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *MissionRun) GetParentMissionId() string {
	if x != nil {
		return x.ParentMissionId
	}
	return ""
}

// AgentRun represents: Single execution of an agent within a mission
type AgentRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	AgentName    string  `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Status       *string `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	StartedAt    *int64  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt  *int64  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	ErrorMessage *string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// Parent reference
	ParentMissionRunId string `protobuf:"bytes,7,opt,name=parent_mission_run_id,json=parentMissionRunId,proto3" json:"parent_mission_run_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRun) Reset() {
	*x = AgentRun{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRun) ProtoMessage() {}

func (x *AgentRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRun.ProtoReflect.Descriptor instead.
func (*AgentRun) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{7}
}

func (x *AgentRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRun) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentRun) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *AgentRun) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *AgentRun) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *AgentRun) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AgentRun) GetParentMissionRunId() string {
	if x != nil {
		return x.ParentMissionRunId
	}
	return ""
}

// ToolExecution represents: Execution of a security tool
type ToolExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	ToolName    string  `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Command     *string `protobuf:"bytes,3,opt,name=command,proto3,oneof" json:"command,omitempty"`
	ExitCode    *int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	StartedAt   *int64  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt *int64  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Stdout      *string `protobuf:"bytes,7,opt,name=stdout,proto3,oneof" json:"stdout,omitempty"`
	Stderr      *string `protobuf:"bytes,8,opt,name=stderr,proto3,oneof" json:"stderr,omitempty"`
	// Parent reference
	ParentAgentRunId string `protobuf:"bytes,9,opt,name=parent_agent_run_id,json=parentAgentRunId,proto3" json:"parent_agent_run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolExecution) Reset() {
	*x = ToolExecution{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecution) ProtoMessage() {}

func (x *ToolExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecution.ProtoReflect.Descriptor instead.
func (*ToolExecution) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{8}
}

func (x *ToolExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolExecution) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExecution) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *ToolExecution) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ToolExecution) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *ToolExecution) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *ToolExecution) GetStdout() string {
	if x != nil && x.Stdout != nil {
		return *x.Stdout
	}
	return ""
}

func (x *ToolExecution) GetStderr() string {
	if x != nil && x.Stderr != nil {
		return *x.Stderr
	}
	return ""
}

func (x *ToolExecution) GetParentAgentRunId() string {
	if x != nil {
		return x.ParentAgentRunId
	}
	return ""
}

// LlmCall represents: Call to a large language model
type LlmCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Model            string  `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Provider         *string `protobuf:"bytes,3,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	SlotName         *string `protobuf:"bytes,4,opt,name=slot_name,json=slotName,proto3,oneof" json:"slot_name,omitempty"`
	PromptTokens     *int32  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3,oneof" json:"prompt_tokens,omitempty"`
	CompletionTokens *int32  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3,oneof" json:"completion_tokens,omitempty"`
	TotalTokens      *int32  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3,oneof" json:"total_tokens,omitempty"`
	LatencyMs        *int64  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3,oneof" json:"latency_ms,omitempty"`
	StartedAt        *int64  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	// Parent reference
	ParentAgentRunId string `protobuf:"bytes,10,opt,name=parent_agent_run_id,json=parentAgentRunId,proto3" json:"parent_agent_run_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LlmCall) Reset() {
	*x = LlmCall{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmCall) ProtoMessage() {}

func (x *LlmCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmCall.ProtoReflect.Descriptor instead.
func (*LlmCall) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{9}
}

func (x *LlmCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LlmCall) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LlmCall) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *LlmCall) GetSlotName() string {
	if x != nil && x.SlotName != nil {
		return *x.SlotName
	}
	return ""
}

func (x *LlmCall) GetPromptTokens() int32 {
	if x != nil && x.PromptTokens != nil {
		return *x.PromptTokens
	}
	return 0
}

func (x *LlmCall) GetCompletionTokens() int32 {
	if x != nil && x.CompletionTokens != nil {
		return *x.CompletionTokens
	}
	return 0
}

func (x *LlmCall) GetTotalTokens() int32 {
	if x != nil && x.TotalTokens != nil {
		return *x.TotalTokens
	}
	return 0
}

func (x *LlmCall) GetLatencyMs() int64 {
	if x != nil && x.LatencyMs != nil {
		return *x.LatencyMs
	}
	return 0
}

func (x *LlmCall) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *LlmCall) GetParentAgentRunId() string {
	if x != nil {
		return x.ParentAgentRunId
	}
	return ""
}

// Domain represents: Root domain entity (e.g., example.com)
type Domain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Registrar     *string `protobuf:"bytes,3,opt,name=registrar,proto3,oneof" json:"registrar,omitempty"`
	CreatedDate   *int64  `protobuf:"varint,4,opt,name=created_date,json=createdDate,proto3,oneof" json:"created_date,omitempty"`
	ExpiryDate    *int64  `protobuf:"varint,5,opt,name=expiry_date,json=expiryDate,proto3,oneof" json:"expiry_date,omitempty"`
	Nameservers   *string `protobuf:"bytes,6,opt,name=nameservers,proto3,oneof" json:"nameservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{10}
}

func (x *Domain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetRegistrar() string {
	if x != nil && x.Registrar != nil {
		return *x.Registrar
	}
	return ""
}

func (x *Domain) GetCreatedDate() int64 {
	if x != nil && x.CreatedDate != nil {
		return *x.CreatedDate
	}
	return 0
}

func (x *Domain) GetExpiryDate() int64 {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return 0
}

func (x *Domain) GetNameservers() string {
	if x != nil && x.Nameservers != nil {
		return *x.Nameservers
	}
	return ""
}

// Subdomain represents: Subdomain under a root domain
type Subdomain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullName *string `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	// Parent reference
	ParentDomainId string `protobuf:"bytes,4,opt,name=parent_domain_id,json=parentDomainId,proto3" json:"parent_domain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subdomain) Reset() {
	*x = Subdomain{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subdomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subdomain) ProtoMessage() {}

func (x *Subdomain) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subdomain.ProtoReflect.Descriptor instead.
func (*Subdomain) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{11}
}

func (x *Subdomain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subdomain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subdomain) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *Subdomain) GetParentDomainId() string {
	if x != nil {
		return x.ParentDomainId
	}
	return ""
}

// Host represents: IP address or hostname
type Host struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Ip            *string `protobuf:"bytes,2,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Hostname      *string `protobuf:"bytes,3,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	Os            *string `protobuf:"bytes,4,opt,name=os,proto3,oneof" json:"os,omitempty"`
	OsVersion     *string `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3,oneof" json:"os_version,omitempty"`
	MacAddress    *string `protobuf:"bytes,6,opt,name=mac_address,json=macAddress,proto3,oneof" json:"mac_address,omitempty"`
	State         *string `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{12}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *Host) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *Host) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

func (x *Host) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *Host) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// Port represents: Network port on a host
type Port struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Number   int32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Protocol string  `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	State    *string `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Reason   *string `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// Parent reference
	ParentHostId  string `protobuf:"bytes,6,opt,name=parent_host_id,json=parentHostId,proto3" json:"parent_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{13}
}

func (x *Port) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Port) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Port) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Port) GetParentHostId() string {
	if x != nil {
		return x.ParentHostId
	}
	return ""
}

// Service represents: Service running on a port
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Product   *string `protobuf:"bytes,3,opt,name=product,proto3,oneof" json:"product,omitempty"`
	Version   *string `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ExtraInfo *string `protobuf:"bytes,5,opt,name=extra_info,json=extraInfo,proto3,oneof" json:"extra_info,omitempty"`
	Banner    *string `protobuf:"bytes,6,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	Cpe       *string `protobuf:"bytes,7,opt,name=cpe,proto3,oneof" json:"cpe,omitempty"`
	// Parent reference
	ParentPortId  string `protobuf:"bytes,8,opt,name=parent_port_id,json=parentPortId,proto3" json:"parent_port_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{14}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Service) GetExtraInfo() string {
	if x != nil && x.ExtraInfo != nil {
		return *x.ExtraInfo
	}
	return ""
}

func (x *Service) GetBanner() string {
	if x != nil && x.Banner != nil {
		return *x.Banner
	}
	return ""
}

func (x *Service) GetCpe() string {
	if x != nil && x.Cpe != nil {
		return *x.Cpe
	}
	return ""
}

func (x *Service) GetParentPortId() string {
	if x != nil {
		return x.ParentPortId
	}
	return ""
}

// Endpoint represents: Web endpoint or URL
type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Url           string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method        *string `protobuf:"bytes,3,opt,name=method,proto3,oneof" json:"method,omitempty"`
	StatusCode    *int32  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3,oneof" json:"status_code,omitempty"`
	ContentType   *string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	ContentLength *int64  `protobuf:"varint,6,opt,name=content_length,json=contentLength,proto3,oneof" json:"content_length,omitempty"`
	Title         *string `protobuf:"bytes,7,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Parent reference
	ParentServiceId string `protobuf:"bytes,8,opt,name=parent_service_id,json=parentServiceId,proto3" json:"parent_service_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{15}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Endpoint) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *Endpoint) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *Endpoint) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *Endpoint) GetContentLength() int64 {
	if x != nil && x.ContentLength != nil {
		return *x.ContentLength
	}
	return 0
}

func (x *Endpoint) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Endpoint) GetParentServiceId() string {
	if x != nil {
		return x.ParentServiceId
	}
	return ""
}

// Technology represents: Technology/framework detected
type Technology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Category      *string `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Confidence    *int32  `protobuf:"varint,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Cpe           *string `protobuf:"bytes,6,opt,name=cpe,proto3,oneof" json:"cpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Technology) Reset() {
	*x = Technology{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technology) ProtoMessage() {}

func (x *Technology) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technology.ProtoReflect.Descriptor instead.
func (*Technology) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{16}
}

func (x *Technology) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technology) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Technology) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Technology) GetConfidence() int32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Technology) GetCpe() string {
	if x != nil && x.Cpe != nil {
		return *x.Cpe
	}
	return ""
}

// Certificate represents: TLS/SSL certificate
type Certificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Subject           *string `protobuf:"bytes,2,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Issuer            *string `protobuf:"bytes,3,opt,name=issuer,proto3,oneof" json:"issuer,omitempty"`
	SerialNumber      *string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	NotBefore         *int64  `protobuf:"varint,5,opt,name=not_before,json=notBefore,proto3,oneof" json:"not_before,omitempty"`
	NotAfter          *int64  `protobuf:"varint,6,opt,name=not_after,json=notAfter,proto3,oneof" json:"not_after,omitempty"`
	FingerprintSha256 *string `protobuf:"bytes,7,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3,oneof" json:"fingerprint_sha256,omitempty"`
	San               *string `protobuf:"bytes,8,opt,name=san,proto3,oneof" json:"san,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{17}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Certificate) GetIssuer() string {
	if x != nil && x.Issuer != nil {
		return *x.Issuer
	}
	return ""
}

func (x *Certificate) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *Certificate) GetNotBefore() int64 {
	if x != nil && x.NotBefore != nil {
		return *x.NotBefore
	}
	return 0
}

func (x *Certificate) GetNotAfter() int64 {
	if x != nil && x.NotAfter != nil {
		return *x.NotAfter
	}
	return 0
}

func (x *Certificate) GetFingerprintSha256() string {
	if x != nil && x.FingerprintSha256 != nil {
		return *x.FingerprintSha256
	}
	return ""
}

func (x *Certificate) GetSan() string {
	if x != nil && x.San != nil {
		return *x.San
	}
	return ""
}

// Finding represents: Security vulnerability or issue
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Title         string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string  `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Severity      string   `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence    *float64 `protobuf:"fixed64,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Category      *string  `protobuf:"bytes,6,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Subcategory   *string  `protobuf:"bytes,7,opt,name=subcategory,proto3,oneof" json:"subcategory,omitempty"`
	Remediation   *string  `protobuf:"bytes,8,opt,name=remediation,proto3,oneof" json:"remediation,omitempty"`
	CvssScore     *float64 `protobuf:"fixed64,9,opt,name=cvss_score,json=cvssScore,proto3,oneof" json:"cvss_score,omitempty"`
	CveIds        *string  `protobuf:"bytes,10,opt,name=cve_ids,json=cveIds,proto3,oneof" json:"cve_ids,omitempty"`
	CweIds        *string  `protobuf:"bytes,11,opt,name=cwe_ids,json=cweIds,proto3,oneof" json:"cwe_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{18}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Finding) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Finding) GetSubcategory() string {
	if x != nil && x.Subcategory != nil {
		return *x.Subcategory
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil && x.Remediation != nil {
		return *x.Remediation
	}
	return ""
}

func (x *Finding) GetCvssScore() float64 {
	if x != nil && x.CvssScore != nil {
		return *x.CvssScore
	}
	return 0
}

func (x *Finding) GetCveIds() string {
	if x != nil && x.CveIds != nil {
		return *x.CveIds
	}
	return ""
}

func (x *Finding) GetCweIds() string {
	if x != nil && x.CweIds != nil {
		return *x.CweIds
	}
	return ""
}

// Evidence represents: Supporting evidence for a finding
type Evidence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	Type        string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content     *string `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	ContentType *string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	Url         *string `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	// Parent reference
	ParentFindingId string `protobuf:"bytes,6,opt,name=parent_finding_id,json=parentFindingId,proto3" json:"parent_finding_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{19}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Evidence) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Evidence) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *Evidence) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Evidence) GetParentFindingId() string {
	if x != nil {
		return x.ParentFindingId
	}
	return ""
}

// Technique represents: Attack technique (MITRE/Gibson)
type Technique struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties
	TechniqueId   string  `protobuf:"bytes,2,opt,name=technique_id,json=techniqueId,proto3" json:"technique_id,omitempty"`
	Name          string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Taxonomy      *string `protobuf:"bytes,4,opt,name=taxonomy,proto3,oneof" json:"taxonomy,omitempty"`
	Tactic        *string `protobuf:"bytes,5,opt,name=tactic,proto3,oneof" json:"tactic,omitempty"`
	Description   *string `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string `protobuf:"bytes,7,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Technique) Reset() {
	*x = Technique{}
	mi := &file_api_proto_taxonomy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technique) ProtoMessage() {}

func (x *Technique) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taxonomy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technique.ProtoReflect.Descriptor instead.
func (*Technique) Descriptor() ([]byte, []int) {
	return file_api_proto_taxonomy_proto_rawDescGZIP(), []int{20}
}

func (x *Technique) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technique) GetTechniqueId() string {
	if x != nil {
		return x.TechniqueId
	}
	return ""
}

func (x *Technique) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technique) GetTaxonomy() string {
	if x != nil && x.Taxonomy != nil {
		return *x.Taxonomy
	}
	return ""
}

func (x *Technique) GetTactic() string {
	if x != nil && x.Tactic != nil {
		return *x.Tactic
	}
	return ""
}

func (x *Technique) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Technique) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

var File_api_proto_taxonomy_proto protoreflect.FileDescriptor

const file_api_proto_taxonomy_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/taxonomy.proto\x12\btaxonomy\"\xd0\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12)\n" +
	"\x0ftimestamp_value\x18\x06 \x01(\x03H\x00R\x0etimestampValue\x124\n" +
	"\n" +
	"list_value\x18\a \x01(\v2\x13.taxonomy.ListValueH\x00R\tlistValue\x121\n" +
	"\tmap_value\x18\b \x01(\v2\x12.taxonomy.MapValueH\x00R\bmapValueB\x06\n" +
	"\x04kind\"4\n" +
	"\tListValue\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.taxonomy.ValueR\x06values\"\x8e\x01\n" +
	"\bMapValue\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.taxonomy.MapValue.FieldsEntryR\x06fields\x1aJ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.taxonomy.ValueR\x05value:\x028\x01\"\xe7\x04\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12C\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2#.taxonomy.GraphNode.PropertiesEntryR\n" +
	"properties\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x12$\n" +
	"\vparent_type\x18\x05 \x01(\tH\x01R\n" +
	"parentType\x88\x01\x01\x124\n" +
	"\x13parent_relationship\x18\x06 \x01(\tH\x02R\x12parentRelationship\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"mission_id\x18\n" +
	" \x01(\tR\tmissionId\x12$\n" +
	"\x0emission_run_id\x18\v \x01(\tR\fmissionRunId\x12 \n" +
	"\fagent_run_id\x18\f \x01(\tR\n" +
	"agentRunId\x12#\n" +
	"\rdiscovered_by\x18\r \x01(\tR\fdiscoveredBy\x12#\n" +
	"\rdiscovered_at\x18\x0e \x01(\x03R\fdiscoveredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x1aN\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.taxonomy.ValueR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_parent_typeB\x16\n" +
	"\x14_parent_relationship\"\xf4\x02\n" +
	"\fRelationship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12F\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2&.taxonomy.Relationship.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1d\n" +
	"\n" +
	"mission_id\x18\n" +
	" \x01(\tR\tmissionId\x12$\n" +
	"\x0emission_run_id\x18\v \x01(\tR\fmissionRunId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x1aN\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.taxonomy.ValueR\x05value:\x028\x01\"\x90\x02\n" +
	"\aMission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x00R\x06status\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03H\x02R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\a \x01(\x03H\x03R\vcompletedAt\x88\x01\x01B\t\n" +
	"\a_statusB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\xfb\x01\n" +
	"\n" +
	"MissionRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"run_number\x18\x02 \x01(\x05R\trunNumber\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03H\x01R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x05 \x01(\x03H\x02R\vcompletedAt\x88\x01\x01\x12*\n" +
	"\x11parent_mission_id\x18\x06 \x01(\tR\x0fparentMissionIdB\t\n" +
	"\a_statusB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\xbc\x02\n" +
	"\bAgentRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03H\x01R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x05 \x01(\x03H\x02R\vcompletedAt\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x06 \x01(\tH\x03R\ferrorMessage\x88\x01\x01\x121\n" +
	"\x15parent_mission_run_id\x18\a \x01(\tR\x12parentMissionRunIdB\t\n" +
	"\a_statusB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_atB\x10\n" +
	"\x0e_error_message\"\x82\x03\n" +
	"\rToolExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1d\n" +
	"\acommand\x18\x03 \x01(\tH\x00R\acommand\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x04 \x01(\x05H\x01R\bexitCode\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03H\x02R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x06 \x01(\x03H\x03R\vcompletedAt\x88\x01\x01\x12\x1b\n" +
	"\x06stdout\x18\a \x01(\tH\x04R\x06stdout\x88\x01\x01\x12\x1b\n" +
	"\x06stderr\x18\b \x01(\tH\x05R\x06stderr\x88\x01\x01\x12-\n" +
	"\x13parent_agent_run_id\x18\t \x01(\tR\x10parentAgentRunIdB\n" +
	"\n" +
	"\b_commandB\f\n" +
	"\n" +
	"_exit_codeB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_atB\t\n" +
	"\a_stdoutB\t\n" +
	"\a_stderr\"\xdf\x03\n" +
	"\aLlmCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\bprovider\x18\x03 \x01(\tH\x00R\bprovider\x88\x01\x01\x12 \n" +
	"\tslot_name\x18\x04 \x01(\tH\x01R\bslotName\x88\x01\x01\x12(\n" +
	"\rprompt_tokens\x18\x05 \x01(\x05H\x02R\fpromptTokens\x88\x01\x01\x120\n" +
	"\x11completion_tokens\x18\x06 \x01(\x05H\x03R\x10completionTokens\x88\x01\x01\x12&\n" +
	"\ftotal_tokens\x18\a \x01(\x05H\x04R\vtotalTokens\x88\x01\x01\x12\"\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x03H\x05R\tlatencyMs\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\t \x01(\x03H\x06R\tstartedAt\x88\x01\x01\x12-\n" +
	"\x13parent_agent_run_id\x18\n" +
	" \x01(\tR\x10parentAgentRunIdB\v\n" +
	"\t_providerB\f\n" +
	"\n" +
	"_slot_nameB\x10\n" +
	"\x0e_prompt_tokensB\x14\n" +
	"\x12_completion_tokensB\x0f\n" +
	"\r_total_tokensB\r\n" +
	"\v_latency_msB\r\n" +
	"\v_started_at\"\x83\x02\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tregistrar\x18\x03 \x01(\tH\x00R\tregistrar\x88\x01\x01\x12&\n" +
	"\fcreated_date\x18\x04 \x01(\x03H\x01R\vcreatedDate\x88\x01\x01\x12$\n" +
	"\vexpiry_date\x18\x05 \x01(\x03H\x02R\n" +
	"expiryDate\x88\x01\x01\x12%\n" +
	"\vnameservers\x18\x06 \x01(\tH\x03R\vnameservers\x88\x01\x01B\f\n" +
	"\n" +
	"_registrarB\x0f\n" +
	"\r_created_dateB\x0e\n" +
	"\f_expiry_dateB\x0e\n" +
	"\f_nameservers\"\x89\x01\n" +
	"\tSubdomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\tfull_name\x18\x03 \x01(\tH\x00R\bfullName\x88\x01\x01\x12(\n" +
	"\x10parent_domain_id\x18\x04 \x01(\tR\x0eparentDomainIdB\f\n" +
	"\n" +
	"_full_name\"\x8a\x02\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x02ip\x18\x02 \x01(\tH\x00R\x02ip\x88\x01\x01\x12\x1f\n" +
	"\bhostname\x18\x03 \x01(\tH\x01R\bhostname\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x04 \x01(\tH\x02R\x02os\x88\x01\x01\x12\"\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tH\x03R\tosVersion\x88\x01\x01\x12$\n" +
	"\vmac_address\x18\x06 \x01(\tH\x04R\n" +
	"macAddress\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x05R\x05state\x88\x01\x01B\x05\n" +
	"\x03_ipB\v\n" +
	"\t_hostnameB\x05\n" +
	"\x03_osB\r\n" +
	"\v_os_versionB\x0e\n" +
	"\f_mac_addressB\b\n" +
	"\x06_state\"\xbd\x01\n" +
	"\x04Port\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x00R\x05state\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x05 \x01(\tH\x01R\x06reason\x88\x01\x01\x12$\n" +
	"\x0eparent_host_id\x18\x06 \x01(\tR\fparentHostIdB\b\n" +
	"\x06_stateB\t\n" +
	"\a_reason\"\xa3\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\aproduct\x18\x03 \x01(\tH\x00R\aproduct\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\tH\x01R\aversion\x88\x01\x01\x12\"\n" +
	"\n" +
	"extra_info\x18\x05 \x01(\tH\x02R\textraInfo\x88\x01\x01\x12\x1b\n" +
	"\x06banner\x18\x06 \x01(\tH\x03R\x06banner\x88\x01\x01\x12\x15\n" +
	"\x03cpe\x18\a \x01(\tH\x04R\x03cpe\x88\x01\x01\x12$\n" +
	"\x0eparent_port_id\x18\b \x01(\tR\fparentPortIdB\n" +
	"\n" +
	"\b_productB\n" +
	"\n" +
	"\b_versionB\r\n" +
	"\v_extra_infoB\t\n" +
	"\a_bannerB\x06\n" +
	"\x04_cpe\"\xd3\x02\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\x06method\x18\x03 \x01(\tH\x00R\x06method\x88\x01\x01\x12$\n" +
	"\vstatus_code\x18\x04 \x01(\x05H\x01R\n" +
	"statusCode\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x05 \x01(\tH\x02R\vcontentType\x88\x01\x01\x12*\n" +
	"\x0econtent_length\x18\x06 \x01(\x03H\x03R\rcontentLength\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\a \x01(\tH\x04R\x05title\x88\x01\x01\x12*\n" +
	"\x11parent_service_id\x18\b \x01(\tR\x0fparentServiceIdB\t\n" +
	"\a_methodB\x0e\n" +
	"\f_status_codeB\x0f\n" +
	"\r_content_typeB\x11\n" +
	"\x0f_content_lengthB\b\n" +
	"\x06_title\"\xdc\x01\n" +
	"\n" +
	"Technology\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x00R\aversion\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x01R\bcategory\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x05H\x02R\n" +
	"confidence\x88\x01\x01\x12\x15\n" +
	"\x03cpe\x18\x06 \x01(\tH\x03R\x03cpe\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\v\n" +
	"\t_categoryB\r\n" +
	"\v_confidenceB\x06\n" +
	"\x04_cpe\"\xf9\x02\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\asubject\x18\x02 \x01(\tH\x00R\asubject\x88\x01\x01\x12\x1b\n" +
	"\x06issuer\x18\x03 \x01(\tH\x01R\x06issuer\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x04 \x01(\tH\x02R\fserialNumber\x88\x01\x01\x12\"\n" +
	"\n" +
	"not_before\x18\x05 \x01(\x03H\x03R\tnotBefore\x88\x01\x01\x12 \n" +
	"\tnot_after\x18\x06 \x01(\x03H\x04R\bnotAfter\x88\x01\x01\x122\n" +
	"\x12fingerprint_sha256\x18\a \x01(\tH\x05R\x11fingerprintSha256\x88\x01\x01\x12\x15\n" +
	"\x03san\x18\b \x01(\tH\x06R\x03san\x88\x01\x01B\n" +
	"\n" +
	"\b_subjectB\t\n" +
	"\a_issuerB\x10\n" +
	"\x0e_serial_numberB\r\n" +
	"\v_not_beforeB\f\n" +
	"\n" +
	"_not_afterB\x15\n" +
	"\x13_fingerprint_sha256B\x06\n" +
	"\x04_san\"\xd9\x03\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01H\x01R\n" +
	"confidence\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x06 \x01(\tH\x02R\bcategory\x88\x01\x01\x12%\n" +
	"\vsubcategory\x18\a \x01(\tH\x03R\vsubcategory\x88\x01\x01\x12%\n" +
	"\vremediation\x18\b \x01(\tH\x04R\vremediation\x88\x01\x01\x12\"\n" +
	"\n" +
	"cvss_score\x18\t \x01(\x01H\x05R\tcvssScore\x88\x01\x01\x12\x1c\n" +
	"\acve_ids\x18\n" +
	" \x01(\tH\x06R\x06cveIds\x88\x01\x01\x12\x1c\n" +
	"\acwe_ids\x18\v \x01(\tH\aR\x06cweIds\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_confidenceB\v\n" +
	"\t_categoryB\x0e\n" +
	"\f_subcategoryB\x0e\n" +
	"\f_remediationB\r\n" +
	"\v_cvss_scoreB\n" +
	"\n" +
	"\b_cve_idsB\n" +
	"\n" +
	"\b_cwe_ids\"\xdd\x01\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x00R\acontent\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x04 \x01(\tH\x01R\vcontentType\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x02R\x03url\x88\x01\x01\x12*\n" +
	"\x11parent_finding_id\x18\x06 \x01(\tR\x0fparentFindingIdB\n" +
	"\n" +
	"\b_contentB\x0f\n" +
	"\r_content_typeB\x06\n" +
	"\x04_url\"\xfe\x01\n" +
	"\tTechnique\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftechnique_id\x18\x02 \x01(\tR\vtechniqueId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\btaxonomy\x18\x04 \x01(\tH\x00R\btaxonomy\x88\x01\x01\x12\x1b\n" +
	"\x06tactic\x18\x05 \x01(\tH\x01R\x06tactic\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\a \x01(\tH\x03R\x03url\x88\x01\x01B\v\n" +
	"\t_taxonomyB\t\n" +
	"\a_tacticB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_url*\x82\x04\n" +
	"\fCoreNodeType\x12\x1e\n" +
	"\x1aCORE_NODE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CORE_NODE_TYPE_MISSION\x10\x01\x12\x1e\n" +
	"\x1aCORE_NODE_TYPE_MISSION_RUN\x10\x02\x12\x1c\n" +
	"\x18CORE_NODE_TYPE_AGENT_RUN\x10\x03\x12!\n" +
	"\x1dCORE_NODE_TYPE_TOOL_EXECUTION\x10\x04\x12\x1b\n" +
	"\x17CORE_NODE_TYPE_LLM_CALL\x10\x05\x12\x19\n" +
	"\x15CORE_NODE_TYPE_DOMAIN\x10\x06\x12\x1c\n" +
	"\x18CORE_NODE_TYPE_SUBDOMAIN\x10\a\x12\x17\n" +
	"\x13CORE_NODE_TYPE_HOST\x10\b\x12\x17\n" +
	"\x13CORE_NODE_TYPE_PORT\x10\t\x12\x1a\n" +
	"\x16CORE_NODE_TYPE_SERVICE\x10\n" +
	"\x12\x1b\n" +
	"\x17CORE_NODE_TYPE_ENDPOINT\x10\v\x12\x1d\n" +
	"\x19CORE_NODE_TYPE_TECHNOLOGY\x10\f\x12\x1e\n" +
	"\x1aCORE_NODE_TYPE_CERTIFICATE\x10\r\x12\x1a\n" +
	"\x16CORE_NODE_TYPE_FINDING\x10\x0e\x12\x1b\n" +
	"\x17CORE_NODE_TYPE_EVIDENCE\x10\x0f\x12\x1c\n" +
	"\x18CORE_NODE_TYPE_TECHNIQUE\x10\x10*\xb5\x05\n" +
	"\x10CoreRelationType\x12\"\n" +
	"\x1eCORE_RELATION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCORE_RELATION_TYPE_HAS_RUN\x10\x01\x12)\n" +
	"%CORE_RELATION_TYPE_CONTAINS_AGENT_RUN\x10\x02\x12$\n" +
	" CORE_RELATION_TYPE_EXECUTED_TOOL\x10\x03\x12 \n" +
	"\x1cCORE_RELATION_TYPE_MADE_CALL\x10\x04\x12#\n" +
	"\x1fCORE_RELATION_TYPE_DELEGATED_TO\x10\x05\x12$\n" +
	" CORE_RELATION_TYPE_HAS_SUBDOMAIN\x10\x06\x12\"\n" +
	"\x1eCORE_RELATION_TYPE_RESOLVES_TO\x10\a\x12\x1f\n" +
	"\x1bCORE_RELATION_TYPE_HAS_PORT\x10\b\x12#\n" +
	"\x1fCORE_RELATION_TYPE_RUNS_SERVICE\x10\t\x12#\n" +
	"\x1fCORE_RELATION_TYPE_HAS_ENDPOINT\x10\n" +
	"\x12&\n" +
	"\"CORE_RELATION_TYPE_USES_TECHNOLOGY\x10\v\x12)\n" +
	"%CORE_RELATION_TYPE_SERVES_CERTIFICATE\x10\f\x12*\n" +
	"&CORE_RELATION_TYPE_D_I_S_C_O_V_E_R_E_D\x10\r\x12$\n" +
	" CORE_RELATION_TYPE_A_F_F_E_C_T_S\x10\x0e\x12#\n" +
	"\x1fCORE_RELATION_TYPE_HAS_EVIDENCE\x10\x0f\x12%\n" +
	"!CORE_RELATION_TYPE_USES_TECHNIQUE\x10\x10\x12\x1f\n" +
	"\x1bCORE_RELATION_TYPE_LEADS_TO\x10\x11B/Z-github.com/zero-day-ai/sdk/api/gen/taxonomypbb\x06proto3"

var (
	file_api_proto_taxonomy_proto_rawDescOnce sync.Once
	file_api_proto_taxonomy_proto_rawDescData []byte
)

func file_api_proto_taxonomy_proto_rawDescGZIP() []byte {
	file_api_proto_taxonomy_proto_rawDescOnce.Do(func() {
		file_api_proto_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_taxonomy_proto_rawDesc), len(file_api_proto_taxonomy_proto_rawDesc)))
	})
	return file_api_proto_taxonomy_proto_rawDescData
}

var file_api_proto_taxonomy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_taxonomy_proto_goTypes = []any{
	(CoreNodeType)(0),     // 0: taxonomy.CoreNodeType
	(CoreRelationType)(0), // 1: taxonomy.CoreRelationType
	(*Value)(nil),         // 2: taxonomy.Value
	(*ListValue)(nil),     // 3: taxonomy.ListValue
	(*MapValue)(nil),      // 4: taxonomy.MapValue
	(*GraphNode)(nil),     // 5: taxonomy.GraphNode
	(*Relationship)(nil),  // 6: taxonomy.Relationship
	(*Mission)(nil),       // 7: taxonomy.Mission
	(*MissionRun)(nil),    // 8: taxonomy.MissionRun
	(*AgentRun)(nil),      // 9: taxonomy.AgentRun
	(*ToolExecution)(nil), // 10: taxonomy.ToolExecution
	(*LlmCall)(nil),       // 11: taxonomy.LlmCall
	(*Domain)(nil),        // 12: taxonomy.Domain
	(*Subdomain)(nil),     // 13: taxonomy.Subdomain
	(*Host)(nil),          // 14: taxonomy.Host
	(*Port)(nil),          // 15: taxonomy.Port
	(*Service)(nil),       // 16: taxonomy.Service
	(*Endpoint)(nil),      // 17: taxonomy.Endpoint
	(*Technology)(nil),    // 18: taxonomy.Technology
	(*Certificate)(nil),   // 19: taxonomy.Certificate
	(*Finding)(nil),       // 20: taxonomy.Finding
	(*Evidence)(nil),      // 21: taxonomy.Evidence
	(*Technique)(nil),     // 22: taxonomy.Technique
	nil,                   // 23: taxonomy.MapValue.FieldsEntry
	nil,                   // 24: taxonomy.GraphNode.PropertiesEntry
	nil,                   // 25: taxonomy.Relationship.PropertiesEntry
}
var file_api_proto_taxonomy_proto_depIdxs = []int32{
	3,  // 0: taxonomy.Value.list_value:type_name -> taxonomy.ListValue
	4,  // 1: taxonomy.Value.map_value:type_name -> taxonomy.MapValue
	2,  // 2: taxonomy.ListValue.values:type_name -> taxonomy.Value
	23, // 3: taxonomy.MapValue.fields:type_name -> taxonomy.MapValue.FieldsEntry
	24, // 4: taxonomy.GraphNode.properties:type_name -> taxonomy.GraphNode.PropertiesEntry
	25, // 5: taxonomy.Relationship.properties:type_name -> taxonomy.Relationship.PropertiesEntry
	2,  // 6: taxonomy.MapValue.FieldsEntry.value:type_name -> taxonomy.Value
	2,  // 7: taxonomy.GraphNode.PropertiesEntry.value:type_name -> taxonomy.Value
	2,  // 8: taxonomy.Relationship.PropertiesEntry.value:type_name -> taxonomy.Value
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_taxonomy_proto_init() }
func file_api_proto_taxonomy_proto_init() {
	if File_api_proto_taxonomy_proto != nil {
		return
	}
	file_api_proto_taxonomy_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
	}
	file_api_proto_taxonomy_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_proto_taxonomy_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_taxonomy_proto_rawDesc), len(file_api_proto_taxonomy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_taxonomy_proto_goTypes,
		DependencyIndexes: file_api_proto_taxonomy_proto_depIdxs,
		EnumInfos:         file_api_proto_taxonomy_proto_enumTypes,
		MessageInfos:      file_api_proto_taxonomy_proto_msgTypes,
	}.Build()
	File_api_proto_taxonomy_proto = out.File
	file_api_proto_taxonomy_proto_goTypes = nil
	file_api_proto_taxonomy_proto_depIdxs = nil
}
