// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 3.0.0
// Generated at: 2026-01-26T22:06:24Z

package graphrag

// ==================== NODE TYPE CONSTANTS ====================

// Node type constants for compile-time safety.
const (
	// NodeTypeMission is the "mission" node type.
	NodeTypeMission = "mission"
	// NodeTypeMissionRun is the "mission_run" node type.
	NodeTypeMissionRun = "mission_run"
	// NodeTypeAgentRun is the "agent_run" node type.
	NodeTypeAgentRun = "agent_run"
	// NodeTypeToolExecution is the "tool_execution" node type.
	NodeTypeToolExecution = "tool_execution"
	// NodeTypeLlmCall is the "llm_call" node type.
	NodeTypeLlmCall = "llm_call"
	// NodeTypeDomain is the "domain" node type.
	NodeTypeDomain = "domain"
	// NodeTypeSubdomain is the "subdomain" node type.
	NodeTypeSubdomain = "subdomain"
	// NodeTypeHost is the "host" node type.
	NodeTypeHost = "host"
	// NodeTypePort is the "port" node type.
	NodeTypePort = "port"
	// NodeTypeService is the "service" node type.
	NodeTypeService = "service"
	// NodeTypeEndpoint is the "endpoint" node type.
	NodeTypeEndpoint = "endpoint"
	// NodeTypeTechnology is the "technology" node type.
	NodeTypeTechnology = "technology"
	// NodeTypeCertificate is the "certificate" node type.
	NodeTypeCertificate = "certificate"
	// NodeTypeFinding is the "finding" node type.
	NodeTypeFinding = "finding"
	// NodeTypeEvidence is the "evidence" node type.
	NodeTypeEvidence = "evidence"
	// NodeTypeTechnique is the "technique" node type.
	NodeTypeTechnique = "technique"
)

// ==================== RELATIONSHIP TYPE CONSTANTS ====================

// Relationship type constants for compile-time safety.
const (
	// RelTypeHASRUN is the "HAS_RUN" relationship type.
	RelTypeHASRUN = "HAS_RUN"
	// RelTypeCONTAINSAGENTRUN is the "CONTAINS_AGENT_RUN" relationship type.
	RelTypeCONTAINSAGENTRUN = "CONTAINS_AGENT_RUN"
	// RelTypeEXECUTEDTOOL is the "EXECUTED_TOOL" relationship type.
	RelTypeEXECUTEDTOOL = "EXECUTED_TOOL"
	// RelTypeMADECALL is the "MADE_CALL" relationship type.
	RelTypeMADECALL = "MADE_CALL"
	// RelTypeDELEGATEDTO is the "DELEGATED_TO" relationship type.
	RelTypeDELEGATEDTO = "DELEGATED_TO"
	// RelTypeHASSUBDOMAIN is the "HAS_SUBDOMAIN" relationship type.
	RelTypeHASSUBDOMAIN = "HAS_SUBDOMAIN"
	// RelTypeRESOLVESTO is the "RESOLVES_TO" relationship type.
	RelTypeRESOLVESTO = "RESOLVES_TO"
	// RelTypeHASPORT is the "HAS_PORT" relationship type.
	RelTypeHASPORT = "HAS_PORT"
	// RelTypeRUNSSERVICE is the "RUNS_SERVICE" relationship type.
	RelTypeRUNSSERVICE = "RUNS_SERVICE"
	// RelTypeHASENDPOINT is the "HAS_ENDPOINT" relationship type.
	RelTypeHASENDPOINT = "HAS_ENDPOINT"
	// RelTypeUSESTECHNOLOGY is the "USES_TECHNOLOGY" relationship type.
	RelTypeUSESTECHNOLOGY = "USES_TECHNOLOGY"
	// RelTypeSERVESCERTIFICATE is the "SERVES_CERTIFICATE" relationship type.
	RelTypeSERVESCERTIFICATE = "SERVES_CERTIFICATE"
	// RelTypeDISCOVERED is the "DISCOVERED" relationship type.
	RelTypeDISCOVERED = "DISCOVERED"
	// RelTypeAFFECTS is the "AFFECTS" relationship type.
	RelTypeAFFECTS = "AFFECTS"
	// RelTypeHASEVIDENCE is the "HAS_EVIDENCE" relationship type.
	RelTypeHASEVIDENCE = "HAS_EVIDENCE"
	// RelTypeUSESTECHNIQUE is the "USES_TECHNIQUE" relationship type.
	RelTypeUSESTECHNIQUE = "USES_TECHNIQUE"
	// RelTypeLEADSTO is the "LEADS_TO" relationship type.
	RelTypeLEADSTO = "LEADS_TO"
)

// ==================== CORE TYPES MAP ====================

// CoreTypes is a set of all core (validated) node types.
var CoreTypes = map[string]bool{
	"mission":        true,
	"mission_run":    true,
	"agent_run":      true,
	"tool_execution": true,
	"llm_call":       true,
	"domain":         true,
	"subdomain":      true,
	"host":           true,
	"port":           true,
	"service":        true,
	"endpoint":       true,
	"technology":     true,
	"certificate":    true,
	"finding":        true,
	"evidence":       true,
	"technique":      true,
}

// IsCoreType returns true if the node type is a core (validated) type.
func IsCoreType(nodeType string) bool {
	return CoreTypes[nodeType]
}

// ==================== PARENT REQUIREMENTS ====================

// ParentRequirement defines the parent relationship for a node type.
type ParentRequirement struct {
	ParentType   string
	Relationship string
	Required     bool
}

// ParentRequirements maps node types to their parent requirements.
var ParentRequirements = map[string]ParentRequirement{
	"mission_run": {
		ParentType:   "mission",
		Relationship: "HAS_RUN",
		Required:     true,
	},
	"agent_run": {
		ParentType:   "mission_run",
		Relationship: "CONTAINS_AGENT_RUN",
		Required:     true,
	},
	"tool_execution": {
		ParentType:   "agent_run",
		Relationship: "EXECUTED_TOOL",
		Required:     true,
	},
	"llm_call": {
		ParentType:   "agent_run",
		Relationship: "MADE_CALL",
		Required:     true,
	},
	"subdomain": {
		ParentType:   "domain",
		Relationship: "HAS_SUBDOMAIN",
		Required:     true,
	},
	"port": {
		ParentType:   "host",
		Relationship: "HAS_PORT",
		Required:     true,
	},
	"service": {
		ParentType:   "port",
		Relationship: "RUNS_SERVICE",
		Required:     true,
	},
	"endpoint": {
		ParentType:   "service",
		Relationship: "HAS_ENDPOINT",
		Required:     true,
	},
	"evidence": {
		ParentType:   "finding",
		Relationship: "HAS_EVIDENCE",
		Required:     true,
	},
}

// GetParentRequirement returns the parent requirement for a node type.
func GetParentRequirement(nodeType string) (ParentRequirement, bool) {
	req, ok := ParentRequirements[nodeType]
	return req, ok
}

// ==================== ALL NODE TYPES ====================

// AllNodeTypes is a list of all core node type names.
var AllNodeTypes = []string{
	"mission",
	"mission_run",
	"agent_run",
	"tool_execution",
	"llm_call",
	"domain",
	"subdomain",
	"host",
	"port",
	"service",
	"endpoint",
	"technology",
	"certificate",
	"finding",
	"evidence",
	"technique",
}

// ==================== ALL RELATIONSHIP TYPES ====================

// AllRelationshipTypes is a list of all core relationship type names.
var AllRelationshipTypes = []string{
	"HAS_RUN",
	"CONTAINS_AGENT_RUN",
	"EXECUTED_TOOL",
	"MADE_CALL",
	"DELEGATED_TO",
	"HAS_SUBDOMAIN",
	"RESOLVES_TO",
	"HAS_PORT",
	"RUNS_SERVICE",
	"HAS_ENDPOINT",
	"USES_TECHNOLOGY",
	"SERVES_CERTIFICATE",
	"DISCOVERED",
	"AFFECTS",
	"HAS_EVIDENCE",
	"USES_TECHNIQUE",
	"LEADS_TO",
}
