// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 3.0.0
// Generated at: 2026-01-26T14:37:33Z

package graphrag

import (
	"github.com/google/uuid"
	"github.com/zero-day-ai/sdk/api/gen/taxonomypb"
)

// ==================== NODE CREATION HELPERS ====================
//
// These helpers auto-generate UUIDs and set up parent relationships.
// Use these instead of manually creating protobuf messages.
//
// Root types (no parent):
//   - NewHost(ip string) *taxonomypb.Host
//   - NewDomain(name string) *taxonomypb.Domain
//   - etc.
//
// Child types (has parent):
//   - NewPort(parent *taxonomypb.Host, number int32, protocol string) *taxonomypb.Port
//   - NewService(parent *taxonomypb.Port, name string) *taxonomypb.Service
//   - etc.
//
// All helpers:
//   1. Generate a UUID and assign to Id field
//   2. Set required properties
//   3. For child types: copy parent.Id to the parent reference field
//   4. Panic if parent.Id is nil (must use NewXxx() or set Id manually)
//

// NewMission creates a Mission with auto-generated UUID.
func NewMission(name string, target string) *taxonomypb.Mission {
	id := uuid.New().String()
	return &taxonomypb.Mission{
		Id:     id,
		Name:   name,
		Target: target,
	}
}

// NewMissionRun creates a MissionRun linked to parent Mission.
// Panics if parent.Id is empty.
func NewMissionRun(parent *taxonomypb.Mission, run_number int32) *taxonomypb.MissionRun {
	if parent.Id == "" {
		panic("parent Mission must have Id set - use NewMission() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.MissionRun{
		Id:              id,
		ParentMissionId: parent.Id,
		RunNumber:       run_number,
	}
}

// NewAgentRun creates a AgentRun linked to parent MissionRun.
// Panics if parent.Id is empty.
func NewAgentRun(parent *taxonomypb.MissionRun, agent_name string) *taxonomypb.AgentRun {
	if parent.Id == "" {
		panic("parent MissionRun must have Id set - use NewMissionRun() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.AgentRun{
		Id:                 id,
		ParentMissionRunId: parent.Id,
		AgentName:          agent_name,
	}
}

// NewToolExecution creates a ToolExecution linked to parent AgentRun.
// Panics if parent.Id is empty.
func NewToolExecution(parent *taxonomypb.AgentRun, tool_name string) *taxonomypb.ToolExecution {
	if parent.Id == "" {
		panic("parent AgentRun must have Id set - use NewAgentRun() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.ToolExecution{
		Id:               id,
		ParentAgentRunId: parent.Id,
		ToolName:         tool_name,
	}
}

// NewLlmCall creates a LlmCall linked to parent AgentRun.
// Panics if parent.Id is empty.
func NewLlmCall(parent *taxonomypb.AgentRun, model string) *taxonomypb.LlmCall {
	if parent.Id == "" {
		panic("parent AgentRun must have Id set - use NewAgentRun() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.LlmCall{
		Id:               id,
		ParentAgentRunId: parent.Id,
		Model:            model,
	}
}

// NewDomain creates a Domain with auto-generated UUID.
func NewDomain(name string) *taxonomypb.Domain {
	id := uuid.New().String()
	return &taxonomypb.Domain{
		Id:   id,
		Name: name,
	}
}

// NewSubdomain creates a Subdomain linked to parent Domain.
// Panics if parent.Id is empty.
func NewSubdomain(parent *taxonomypb.Domain, name string) *taxonomypb.Subdomain {
	if parent.Id == "" {
		panic("parent Domain must have Id set - use NewDomain() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Subdomain{
		Id:             id,
		ParentDomainId: parent.Id,
		Name:           name,
	}
}

// NewHost creates a Host with auto-generated UUID.
func NewHost() *taxonomypb.Host {
	id := uuid.New().String()
	return &taxonomypb.Host{
		Id: id,
	}
}

// NewPort creates a Port linked to parent Host.
// Panics if parent.Id is empty.
func NewPort(parent *taxonomypb.Host, number int32, protocol string) *taxonomypb.Port {
	if parent.Id == "" {
		panic("parent Host must have Id set - use NewHost() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Port{
		Id:           id,
		ParentHostId: parent.Id,
		Number:       number,
		Protocol:     protocol,
	}
}

// NewService creates a Service linked to parent Port.
// Panics if parent.Id is empty.
func NewService(parent *taxonomypb.Port, name string) *taxonomypb.Service {
	if parent.Id == "" {
		panic("parent Port must have Id set - use NewPort() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Service{
		Id:           id,
		ParentPortId: parent.Id,
		Name:         name,
	}
}

// NewEndpoint creates a Endpoint linked to parent Service.
// Panics if parent.Id is empty.
func NewEndpoint(parent *taxonomypb.Service, url string) *taxonomypb.Endpoint {
	if parent.Id == "" {
		panic("parent Service must have Id set - use NewService() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Endpoint{
		Id:              id,
		ParentServiceId: parent.Id,
		Url:             url,
	}
}

// NewTechnology creates a Technology with auto-generated UUID.
func NewTechnology(name string) *taxonomypb.Technology {
	id := uuid.New().String()
	return &taxonomypb.Technology{
		Id:   id,
		Name: name,
	}
}

// NewCertificate creates a Certificate with auto-generated UUID.
func NewCertificate() *taxonomypb.Certificate {
	id := uuid.New().String()
	return &taxonomypb.Certificate{
		Id: id,
	}
}

// NewFinding creates a Finding with auto-generated UUID.
func NewFinding(title string, severity string) *taxonomypb.Finding {
	id := uuid.New().String()
	return &taxonomypb.Finding{
		Id:       id,
		Title:    title,
		Severity: severity,
	}
}

// NewEvidence creates a Evidence linked to parent Finding.
// Panics if parent.Id is empty.
func NewEvidence(parent *taxonomypb.Finding, type_ string) *taxonomypb.Evidence {
	if parent.Id == "" {
		panic("parent Finding must have Id set - use NewFinding() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Evidence{
		Id:              id,
		ParentFindingId: parent.Id,
		Type:            type_,
	}
}

// NewTechnique creates a Technique with auto-generated UUID.
func NewTechnique(technique_id string, name string) *taxonomypb.Technique {
	id := uuid.New().String()
	return &taxonomypb.Technique{
		Id:          id,
		TechniqueId: technique_id,
		Name:        name,
	}
}
