// Code generated by taxonomy-gen. DO NOT EDIT.
// Source: github.com/zero-day-ai/gibson/internal/graphrag/taxonomy
// Taxonomy Version: 0.15.0

package graphrag

// TaxonomyVersion is the version of the taxonomy that these constants were generated from.
// This version is tied to the Gibson binary version.
const TaxonomyVersion = "0.15.0"

// Node type constants
// These constants define the canonical node types in the GraphRAG taxonomy.
const (
	// AgentRun - Single execution run of an agent within a mission
	NodeTypeAgentRun = "agent_run"
	// API - Web API service with multiple endpoints
	NodeTypeApi = "api"
	// Certificate - TLS/SSL certificate discovered on a host or service
	NodeTypeCertificate = "certificate"
	// CloudAsset - Cloud infrastructure resource (AWS, GCP, Azure)
	NodeTypeCloudAsset = "cloud_asset"
	// Domain - Root domain entity representing a registered domain name
	NodeTypeDomain = "domain"
	// Endpoint - Web endpoint or URL discovered through crawling or fuzzing
	NodeTypeEndpoint = "endpoint"
	// Evidence - Supporting evidence for a security finding (requests, responses, screenshots, logs)
	NodeTypeEvidence = "evidence"
	// Finding - Security finding, vulnerability, or security issue discovered during assessment
	NodeTypeFinding = "finding"
	// Host - IP address or hostname representing a network host
	NodeTypeHost = "host"
	// LLMCall - Call to a large language model for analysis, planning, or decision-making
	NodeTypeLlmCall = "llm_call"
	// Mission - Top-level security assessment or penetration testing mission
	NodeTypeMission = "mission"
	// Mitigation - Security control, patch, or remediation measure for a finding
	NodeTypeMitigation = "mitigation"
	// Port - Network port on a host
	NodeTypePort = "port"
	// Service - Service running on a network port
	NodeTypeService = "service"
	// Subdomain - Subdomain discovered under a root domain
	NodeTypeSubdomain = "subdomain"
	// Tactic - Attack tactic representing a high-level adversary goal
	NodeTypeTactic = "tactic"
	// Technique - Attack technique from MITRE ATT&CK, Arcanum PI, or custom taxonomy
	NodeTypeTechnique = "technique"
	// Technology - Software, framework, or technology stack component detected on an asset
	NodeTypeTechnology = "technology"
	// ToolExecution - Execution of a security tool (nmap, nuclei, sqlmap, etc.)
	NodeTypeToolExecution = "tool_execution"
)

// Relationship type constants
// These constants define the canonical relationship types in the GraphRAG taxonomy.
const (
	// AFFECTS - Finding affects a specific asset (endpoint, service, host, or technology)
	RelTypeAffects = "AFFECTS"
	// DISCOVERED - Agent run discovered an asset
	RelTypeDiscovered = "DISCOVERED"
	// EXECUTED_BY - Tool execution was performed by an agent run
	RelTypeExecutedBy = "EXECUTED_BY"
	// EXPLOITS - Finding exploits a vulnerability in a specific technology or service
	RelTypeExploits = "EXPLOITS"
	// HAS_ENDPOINT - Service has a web endpoint or URL
	RelTypeHasEndpoint = "HAS_ENDPOINT"
	// HAS_EVIDENCE - Finding is supported by evidence (request, response, screenshot, etc.)
	RelTypeHasEvidence = "HAS_EVIDENCE"
	// HAS_PORT - Host has an open port
	RelTypeHasPort = "HAS_PORT"
	// HAS_SUBDOMAIN - Domain has a subdomain
	RelTypeHasSubdomain = "HAS_SUBDOMAIN"
	// HOSTS - Cloud asset hosts a service or host instance
	RelTypeHosts = "HOSTS"
	// LEADS_TO - Finding leads to another finding in an attack chain
	RelTypeLeadsTo = "LEADS_TO"
	// MADE_CALL - LLM call was made by an agent run
	RelTypeMadeCall = "MADE_CALL"
	// MITIGATES - Mitigation addresses a specific finding
	RelTypeMitigates = "MITIGATES"
	// PART_OF - Agent run is part of a mission
	RelTypePartOf = "PART_OF"
	// PRODUCED - Tool execution produced a finding
	RelTypeProduced = "PRODUCED"
	// RESOLVES_TO - Domain or subdomain resolves to an IP address (host)
	RelTypeResolvesTo = "RESOLVES_TO"
	// RUNS_SERVICE - Port runs a specific service
	RelTypeRunsService = "RUNS_SERVICE"
	// SERVES_CERTIFICATE - Host serves a TLS/SSL certificate
	RelTypeServesCertificate = "SERVES_CERTIFICATE"
	// SIMILAR_TO - Finding is similar to another finding (bidirectional)
	RelTypeSimilarTo = "SIMILAR_TO"
	// USES_TECHNIQUE - Finding demonstrates the use of a specific attack technique
	RelTypeUsesTechnique = "USES_TECHNIQUE"
	// USES_TECHNOLOGY - Service or endpoint uses a specific technology or framework
	RelTypeUsesTechnology = "USES_TECHNOLOGY"
)

// MITRE ATT&CK Technique ID constants
const (
	// OS Credential Dumping - Adversaries may attempt to dump credentials to obtain account login and credential material
	TechniqueT1003 = "T1003"
	// Data from Local System - Adversaries may search local system sources to find files of interest
	TechniqueT1005 = "T1005"
	// Remote Services - Adversaries may use valid accounts to log into a service that accepts remote connections
	TechniqueT1021 = "T1021"
	// Obfuscated Files or Information - Adversaries may attempt to make an executable or file difficult to discover or analyze
	TechniqueT1027 = "T1027"
	// Exfiltration Over C2 Channel - Adversaries may steal data by exfiltrating it over an existing command and control channel
	TechniqueT1041 = "T1041"
	// Network Service Discovery - Adversaries may attempt to get a listing of services running on remote hosts
	TechniqueT1046 = "T1046"
	// Scheduled Task/Job - Adversaries may abuse task scheduling functionality to facilitate initial or recurring execution ...
	TechniqueT1053 = "T1053"
	// Command and Scripting Interpreter - Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries
	TechniqueT1059 = "T1059"
	// Exploitation for Privilege Escalation - Adversaries may exploit software vulnerabilities to elevate privileges
	TechniqueT1068 = "T1068"
	// Indicator Removal - Adversaries may delete or modify artifacts generated on a system to remove evidence of their pres...
	TechniqueT1070 = "T1070"
	// Application Layer Protocol - Adversaries may communicate using application layer protocols to avoid detection
	TechniqueT1071 = "T1071"
	// Valid Accounts - Adversaries may obtain and abuse credentials of existing accounts to persist in the environment
	TechniqueT1078 = "T1078"
	// Account Discovery - Adversaries may attempt to get a listing of valid accounts
	TechniqueT1087 = "T1087"
	// Brute Force - Adversaries may use brute force techniques to gain access to accounts
	TechniqueT1110 = "T1110"
	// Exploit Public-Facing Application - Adversaries may attempt to exploit weaknesses in an Internet-facing host or system to initially a...
	TechniqueT1190 = "T1190"
	// Exploitation for Client Execution - Adversaries may exploit software vulnerabilities in client applications to execute code
	TechniqueT1203 = "T1203"
	// Data Encrypted for Impact - Adversaries may encrypt data on target systems to interrupt availability
	TechniqueT1486 = "T1486"
	// Endpoint Denial of Service - Adversaries may perform Endpoint Denial of Service attacks to degrade or block availability
	TechniqueT1499 = "T1499"
	// Abuse Elevation Control Mechanism - Adversaries may circumvent mechanisms designed to control elevate privileges to gain higher-level...
	TechniqueT1548 = "T1548"
	// Phishing - Adversaries may send phishing messages to gain access to victim systems
	TechniqueT1566 = "T1566"
	// Lateral Tool Transfer - Adversaries may transfer tools or other files between systems in a compromised environment
	TechniqueT1570 = "T1570"
	// Encrypted Channel - Adversaries may employ a known encryption algorithm to conceal command and control traffic
	TechniqueT1573 = "T1573"
)

// Arcanum Prompt Injection Technique ID constants
const (
	// Encoding Obfuscation - Using alternative encodings to hide malicious intent
	TechniqueARCE001 = "ARC-E001"
	// Language Switching - Using non-English languages to evade language-specific filters
	TechniqueARCE002 = "ARC-E002"
	// Token Smuggling - Hiding instructions within tokenization boundaries or exploiting tokenizer behavior
	TechniqueARCE003 = "ARC-E003"
	// Synonym Substitution - Using synonyms or paraphrasing to bypass keyword-based filters
	TechniqueARCE004 = "ARC-E004"
	// System Manipulation - Intent to manipulate the system's core functionality or behavior
	TechniqueARCI001 = "ARC-I001"
	// Information Extraction - Intent to extract sensitive information or system details
	TechniqueARCI002 = "ARC-I002"
	// Jailbreaking - Intent to bypass safety guardrails and content policies
	TechniqueARCI003 = "ARC-I003"
	// Framing - Using specific context framing to manipulate model behavior
	TechniqueARCT001 = "ARC-T001"
	// Narrative Smuggling - Embedding malicious instructions within seemingly benign narratives
	TechniqueARCT002 = "ARC-T002"
	// Instruction Hierarchy Exploitation - Exploiting instruction priority or precedence to override system directives
	TechniqueARCT003 = "ARC-T003"
	// Payload Splitting - Breaking malicious instructions across multiple interactions to evade detection
	TechniqueARCT004 = "ARC-T004"
	// Delimiter Confusion - Using delimiters or special characters to confuse parsing logic
	TechniqueARCT005 = "ARC-T005"
	// Prompt Injection via External Content - Injecting malicious prompts through external data sources (documents, URLs, databases)
	TechniqueARCT006 = "ARC-T006"
	// Direct User Input - Malicious prompts provided directly through user interface
	TechniqueARCV001 = "ARC-V001"
	// Retrieval Augmentation Poisoning - Injecting malicious prompts through RAG document stores or knowledge bases
	TechniqueARCV002 = "ARC-V002"
	// Tool/Function Call Injection - Injecting malicious prompts through tool outputs or function return values
	TechniqueARCV003 = "ARC-V003"
	// Image-based Injection - Embedding malicious instructions in images for vision-enabled models
	TechniqueARCV004 = "ARC-V004"
)

// Common property name constants
const (
	PropName        = "name"
	PropTitle       = "title"
	PropDescription = "description"
	PropSeverity    = "severity"
	PropConfidence  = "confidence"
	PropCategory    = "category"
	PropURL         = "url"
	PropIP          = "ip"
	PropPort        = "port"
	PropProtocol    = "protocol"
	PropMethod      = "method"
	PropStatusCode  = "status_code"
	PropTimestamp   = "timestamp"
)
