// Code generated by taxonomy-gen. DO NOT EDIT.
// Source: github.com/zero-day-ai/gibson/internal/graphrag/taxonomy
// Taxonomy Version: 2.1.0

package graphrag

// TaxonomyVersion is the version of the taxonomy that these constants were generated from.
// This version is tied to the Gibson binary version.
const TaxonomyVersion = "2.1.0"

// Node type constants
// These constants define the canonical node types in the GraphRAG taxonomy.
const (
	// ========== Core Execution Types ==========
	// AgentRun - Single execution run of an agent within a mission
	NodeTypeAgentRun = "agent_run"
	// Mission - Top-level security assessment or penetration testing mission
	NodeTypeMission = "mission"
	// MissionRun - A single execution of a mission pipeline
	NodeTypeMissionRun = "mission_run"
	// ToolExecution - Execution of a security tool (nmap, nuclei, sqlmap, etc.)
	NodeTypeToolExecution = "tool_execution"
	// LLMCall - Call to a large language model for analysis, planning, or decision-making
	NodeTypeLlmCall = "llm_call"
	// Intelligence - LLM-generated analysis report
	NodeTypeIntelligence = "intelligence"

	// ========== Asset Discovery Types ==========
	// Domain - Root domain entity representing a registered domain name
	NodeTypeDomain = "domain"
	// Subdomain - Subdomain discovered under a root domain
	NodeTypeSubdomain = "subdomain"
	// Host - IP address or hostname representing a network host
	NodeTypeHost = "host"
	// Port - Network port on a host
	NodeTypePort = "port"
	// Service - Service running on a network port
	NodeTypeService = "service"
	// Certificate - TLS/SSL certificate discovered on a host or service
	NodeTypeCertificate = "certificate"
	// Technology - Software, framework, or technology stack component detected on an asset
	NodeTypeTechnology = "technology"

	// ========== Network Infrastructure Types ==========
	// DNSRecord - DNS record (A, AAAA, CNAME, MX, TXT, etc.)
	NodeTypeDNSRecord = "dns_record"
	// Firewall - Network firewall or security appliance
	NodeTypeFirewall = "firewall"
	// FirewallRule - Individual firewall rule or ACL entry
	NodeTypeFirewallRule = "firewall_rule"
	// Router - Network router device
	NodeTypeRouter = "router"
	// Route - Network routing table entry
	NodeTypeRoute = "route"
	// LoadBalancer - Load balancer distributing traffic across backends
	NodeTypeLoadBalancer = "load_balancer"
	// Proxy - HTTP/SOCKS proxy or reverse proxy
	NodeTypeProxy = "proxy"
	// VPN - VPN gateway or endpoint
	NodeTypeVPN = "vpn"
	// Network - Network segment or subnet
	NodeTypeNetwork = "network"
	// VLAN - Virtual LAN
	NodeTypeVLAN = "vlan"
	// NetworkInterface - Network interface card or virtual NIC
	NodeTypeNetworkInterface = "network_interface"
	// NetworkZone - Security zone or trust boundary
	NodeTypeNetworkZone = "network_zone"
	// NetworkACL - Network access control list
	NodeTypeNetworkACL = "network_acl"
	// NATGateway - NAT gateway for outbound traffic
	NodeTypeNATGateway = "nat_gateway"
	// BGPPeer - BGP peering relationship
	NodeTypeBGPPeer = "bgp_peer"

	// ========== Web/API Types ==========
	// API - Web API service with multiple endpoints
	NodeTypeApi = "api"
	// Endpoint - Web endpoint or URL discovered through crawling or fuzzing
	NodeTypeEndpoint = "endpoint"
	// APIEndpoint - RESTful or GraphQL API endpoint
	NodeTypeAPIEndpoint = "api_endpoint"
	// Parameter - Query parameter or path parameter
	NodeTypeParameter = "parameter"
	// Header - HTTP header
	NodeTypeHeader = "header"
	// Cookie - HTTP cookie
	NodeTypeCookie = "cookie"
	// Form - HTML form element
	NodeTypeForm = "form"
	// FormField - Individual form input field
	NodeTypeFormField = "form_field"
	// WebSocket - WebSocket connection endpoint
	NodeTypeWebSocket = "websocket"
	// GraphQLSchema - GraphQL schema definition
	NodeTypeGraphQLSchema = "graphql_schema"
	// GraphQLQuery - GraphQL query operation
	NodeTypeGraphQLQuery = "graphql_query"
	// GraphQLMutation - GraphQL mutation operation
	NodeTypeGraphQLMutation = "graphql_mutation"
	// RESTResource - RESTful resource endpoint
	NodeTypeRESTResource = "rest_resource"
	// HTTPMethod - HTTP method (GET, POST, etc.)
	NodeTypeHTTPMethod = "http_method"
	// ContentType - MIME content type
	NodeTypeContentType = "content_type"
	// CORSPolicy - CORS policy configuration
	NodeTypeCORSPolicy = "cors_policy"
	// RateLimit - Rate limiting configuration
	NodeTypeRateLimit = "rate_limit"
	// RequestBody - HTTP request body schema
	NodeTypeRequestBody = "request_body"

	// ========== Identity & Access Types ==========
	// User - User account or identity
	NodeTypeUser = "user"
	// Group - User group or organizational unit
	NodeTypeGroup = "group"
	// Role - Access control role
	NodeTypeRole = "role"
	// Permission - Individual permission or capability
	NodeTypePermission = "permission"
	// Policy - Access control or security policy
	NodeTypePolicy = "policy"
	// Credential - Username/password or authentication credential
	NodeTypeCredential = "credential"
	// APIKey - API key for authentication
	NodeTypeAPIKey = "api_key"
	// Token - Bearer token or session token
	NodeTypeToken = "token"
	// OAuthClient - OAuth 2.0 client registration
	NodeTypeOAuthClient = "oauth_client"
	// OAuthScope - OAuth 2.0 scope definition
	NodeTypeOAuthScope = "oauth_scope"
	// SAMLProvider - SAML identity provider
	NodeTypeSAMLProvider = "saml_provider"
	// IdentityProvider - Generic identity provider (OIDC, LDAP, etc.)
	NodeTypeIdentityProvider = "identity_provider"
	// ServiceAccount - Service account for machine-to-machine auth
	NodeTypeServiceAccount = "service_account"
	// Session - User session or login session
	NodeTypeSession = "session"
	// AccessKey - Cloud provider access key (AWS, GCP, Azure)
	NodeTypeAccessKey = "access_key"
	// MFADevice - Multi-factor authentication device
	NodeTypeMFADevice = "mfa_device"

	// ========== AI/LLM Types ==========
	// LLM - Large language model (GPT-4, Claude, etc.)
	NodeTypeLLM = "llm"
	// LLMDeployment - Deployed LLM instance or endpoint
	NodeTypeLLMDeployment = "llm_deployment"
	// Prompt - LLM prompt template
	NodeTypePrompt = "prompt"
	// SystemPrompt - System-level LLM instruction
	NodeTypeSystemPrompt = "system_prompt"
	// Guardrail - LLM safety guardrail or content filter
	NodeTypeGuardrail = "guardrail"
	// ContentFilter - Content moderation filter
	NodeTypeContentFilter = "content_filter"
	// LLMResponse - LLM completion response
	NodeTypeLLMResponse = "llm_response"
	// TokenUsage - Token consumption metrics
	NodeTypeTokenUsage = "token_usage"
	// EmbeddingModel - Text embedding model
	NodeTypeEmbeddingModel = "embedding_model"
	// FineTune - Fine-tuned model variant
	NodeTypeFineTune = "fine_tune"
	// ModelRegistry - Model version registry
	NodeTypeModelRegistry = "model_registry"
	// ModelVersion - Specific model version
	NodeTypeModelVersion = "model_version"
	// InferenceEndpoint - Model inference API endpoint
	NodeTypeInferenceEndpoint = "inference_endpoint"
	// BatchJob - Batch inference job
	NodeTypeBatchJob = "batch_job"
	// TrainingRun - Model training run
	NodeTypeTrainingRun = "training_run"
	// Dataset - Training or evaluation dataset
	NodeTypeDataset = "dataset"

	// ========== AI Agent Types ==========
	// AIAgent - AI agent system (autonomous LLM-based agent)
	NodeTypeAIAgent = "ai_agent"
	// AgentConfig - Agent configuration settings
	NodeTypeAgentConfig = "agent_config"
	// AgentMemory - Agent memory store (short-term, long-term)
	NodeTypeAgentMemory = "agent_memory"
	// AgentTool - Tool available to agent
	NodeTypeAgentTool = "agent_tool"
	// Chain - LangChain or agent chain definition
	NodeTypeChain = "chain"
	// Workflow - Agent workflow or automation
	NodeTypeWorkflow = "workflow"
	// Crew - Multi-agent crew or team
	NodeTypeCrew = "crew"
	// AgentTask - Task assigned to agent
	NodeTypeAgentTask = "agent_task"
	// AgentRole - Agent role definition (researcher, analyst, etc.)
	NodeTypeAgentRole = "agent_role"
	// ToolCall - Agent tool invocation
	NodeTypeToolCall = "tool_call"
	// ReasoningStep - Agent reasoning step
	NodeTypeReasoningStep = "reasoning_step"
	// MemoryEntry - Individual memory entry
	NodeTypeMemoryEntry = "memory_entry"
	// AgentLoop - Agent control loop
	NodeTypeAgentLoop = "agent_loop"
	// PlanningStep - Agent planning step
	NodeTypePlanningStep = "planning_step"
	// AgentArtifact - Artifact produced by agent
	NodeTypeAgentArtifact = "agent_artifact"

	// ========== MCP (Model Context Protocol) Types ==========
	// MCPServer - MCP server instance
	NodeTypeMCPServer = "mcp_server"
	// MCPTool - MCP tool definition
	NodeTypeMCPTool = "mcp_tool"
	// MCPResource - MCP resource (file, API, database)
	NodeTypeMCPResource = "mcp_resource"
	// MCPPrompt - MCP prompt template
	NodeTypeMCPPrompt = "mcp_prompt"
	// MCPClient - MCP client connection
	NodeTypeMCPClient = "mcp_client"
	// MCPTransport - MCP transport mechanism
	NodeTypeMCPTransport = "mcp_transport"
	// MCPCapability - MCP capability declaration
	NodeTypeMCPCapability = "mcp_capability"
	// MCPSampling - MCP sampling request
	NodeTypeMCPSampling = "mcp_sampling"
	// MCPRoots - MCP roots list
	NodeTypeMCPRoots = "mcp_roots"

	// ========== RAG (Retrieval-Augmented Generation) Types ==========
	// VectorStore - Vector database or embedding store
	NodeTypeVectorStore = "vector_store"
	// VectorIndex - Vector similarity index
	NodeTypeVectorIndex = "vector_index"
	// Document - Document in RAG knowledge base
	NodeTypeDocument = "document"
	// DocumentChunk - Chunked document segment
	NodeTypeDocumentChunk = "document_chunk"
	// KnowledgeBase - RAG knowledge base
	NodeTypeKnowledgeBase = "knowledge_base"
	// Retriever - Document retrieval component
	NodeTypeRetriever = "retriever"
	// RAGPipeline - End-to-end RAG pipeline
	NodeTypeRAGPipeline = "rag_pipeline"
	// Embedding - Text embedding vector
	NodeTypeEmbedding = "embedding"
	// Reranker - Retrieval reranking model
	NodeTypeReranker = "reranker"
	// ChunkingStrategy - Document chunking strategy
	NodeTypeChunkingStrategy = "chunking_strategy"
	// RetrievalResult - Retrieved document result
	NodeTypeRetrievalResult = "retrieval_result"

	// ========== Data Types ==========
	// Database - Database instance (SQL, NoSQL)
	NodeTypeDatabase = "database"
	// Table - Database table or collection
	NodeTypeTable = "table"
	// Column - Database column or field
	NodeTypeColumn = "column"
	// Index - Database index
	NodeTypeIndex = "index"
	// View - Database view or materialized view
	NodeTypeView = "view"
	// StoredProcedure - Database stored procedure
	NodeTypeStoredProcedure = "stored_procedure"
	// Trigger - Database trigger
	NodeTypeTrigger = "trigger"
	// File - File system file
	NodeTypeFile = "file"
	// StorageBucket - Cloud storage bucket (S3, GCS, Azure Blob)
	NodeTypeStorageBucket = "storage_bucket"
	// Object - Object storage object
	NodeTypeObject = "object"
	// Queue - Message queue
	NodeTypeQueue = "queue"
	// Topic - Pub/sub topic
	NodeTypeTopic = "topic"
	// Stream - Data stream (Kafka, Kinesis)
	NodeTypeStream = "stream"
	// Cache - Cache layer (Redis, Memcached)
	NodeTypeCache = "cache"
	// Schema - Data schema definition
	NodeTypeSchema = "schema"
	// DataPipeline - ETL or data processing pipeline
	NodeTypeDataPipeline = "data_pipeline"

	// ========== Container Types ==========
	// Container - Running container instance
	NodeTypeContainer = "container"
	// ContainerImage - Container image
	NodeTypeContainerImage = "container_image"
	// ContainerRegistry - Container registry (Docker Hub, ECR, GCR)
	NodeTypeContainerRegistry = "container_registry"
	// Dockerfile - Dockerfile build specification
	NodeTypeDockerfile = "dockerfile"

	// ========== Kubernetes Types ==========
	// K8sCluster - Kubernetes cluster
	NodeTypeK8sCluster = "k8s_cluster"
	// K8sNamespace - Kubernetes namespace
	NodeTypeK8sNamespace = "k8s_namespace"
	// K8sPod - Kubernetes pod
	NodeTypeK8sPod = "k8s_pod"
	// K8sDeployment - Kubernetes deployment
	NodeTypeK8sDeployment = "k8s_deployment"
	// K8sService - Kubernetes service
	NodeTypeK8sService = "k8s_service"
	// K8sIngress - Kubernetes ingress
	NodeTypeK8sIngress = "k8s_ingress"
	// K8sConfigMap - Kubernetes ConfigMap
	NodeTypeK8sConfigMap = "k8s_configmap"
	// K8sSecret - Kubernetes secret
	NodeTypeK8sSecret = "k8s_secret"
	// K8sPVC - Kubernetes PersistentVolumeClaim
	NodeTypeK8sPVC = "k8s_pvc"
	// K8sPV - Kubernetes PersistentVolume
	NodeTypeK8sPV = "k8s_pv"
	// K8sStatefulSet - Kubernetes StatefulSet
	NodeTypeK8sStatefulSet = "k8s_statefulset"
	// K8sDaemonSet - Kubernetes DaemonSet
	NodeTypeK8sDaemonSet = "k8s_daemonset"
	// K8sJob - Kubernetes Job
	NodeTypeK8sJob = "k8s_job"
	// K8sCronJob - Kubernetes CronJob
	NodeTypeK8sCronJob = "k8s_cronjob"
	// K8sServiceAccount - Kubernetes ServiceAccount
	NodeTypeK8sServiceAccount = "k8s_serviceaccount"
	// K8sRole - Kubernetes Role
	NodeTypeK8sRole = "k8s_role"
	// K8sRoleBinding - Kubernetes RoleBinding
	NodeTypeK8sRoleBinding = "k8s_rolebinding"
	// K8sClusterRole - Kubernetes ClusterRole
	NodeTypeK8sClusterRole = "k8s_clusterrole"
	// K8sClusterRoleBinding - Kubernetes ClusterRoleBinding
	NodeTypeK8sClusterRoleBinding = "k8s_clusterrolebinding"
	// K8sNetworkPolicy - Kubernetes NetworkPolicy
	NodeTypeK8sNetworkPolicy = "k8s_networkpolicy"
	// K8sLimitRange - Kubernetes LimitRange
	NodeTypeK8sLimitRange = "k8s_limitrange"
	// K8sResourceQuota - Kubernetes ResourceQuota
	NodeTypeK8sResourceQuota = "k8s_resourcequota"

	// ========== Cloud Provider Types ==========
	// CloudAsset - Cloud infrastructure resource (AWS, GCP, Azure)
	NodeTypeCloudAsset = "cloud_asset"
	// CloudAccount - Cloud provider account
	NodeTypeCloudAccount = "cloud_account"
	// CloudVPC - Virtual Private Cloud
	NodeTypeCloudVPC = "cloud_vpc"
	// CloudSubnet - Cloud subnet
	NodeTypeCloudSubnet = "cloud_subnet"
	// CloudSecurityGroup - Cloud security group or firewall
	NodeTypeCloudSecurityGroup = "cloud_security_group"
	// CloudInstance - Cloud compute instance (EC2, GCE, Azure VM)
	NodeTypeCloudInstance = "cloud_instance"
	// CloudFunction - Serverless function (Lambda, Cloud Functions)
	NodeTypeCloudFunction = "cloud_function"
	// CloudStorage - Cloud storage service
	NodeTypeCloudStorage = "cloud_storage"
	// CloudDatabase - Cloud-managed database
	NodeTypeCloudDatabase = "cloud_database"
	// CloudQueue - Cloud message queue service
	NodeTypeCloudQueue = "cloud_queue"
	// CloudAPIGateway - Cloud API gateway
	NodeTypeCloudAPIGateway = "cloud_api_gateway"
	// CloudCDN - Cloud CDN service
	NodeTypeCloudCDN = "cloud_cdn"
	// CloudDNSZone - Cloud DNS zone
	NodeTypeCloudDNSZone = "cloud_dns_zone"
	// CloudCertificate - Cloud-managed certificate
	NodeTypeCloudCertificate = "cloud_certificate"
	// CloudKMSKey - Cloud KMS encryption key
	NodeTypeCloudKMSKey = "cloud_kms_key"
	// CloudIAMRole - Cloud IAM role
	NodeTypeCloudIAMRole = "cloud_iam_role"
	// CloudIAMPolicy - Cloud IAM policy
	NodeTypeCloudIAMPolicy = "cloud_iam_policy"
	// CloudTrail - Cloud audit trail (CloudTrail, Cloud Audit Logs)
	NodeTypeCloudTrail = "cloud_trail"
	// CloudMetric - Cloud monitoring metric
	NodeTypeCloudMetric = "cloud_metric"
	// CloudAlarm - Cloud monitoring alarm
	NodeTypeCloudAlarm = "cloud_alarm"
	// CloudRegion - Cloud provider region
	NodeTypeCloudRegion = "cloud_region"

	// ========== Security Finding Types ==========
	// Finding - Security finding, vulnerability, or security issue discovered during assessment
	NodeTypeFinding = "finding"
	// Evidence - Supporting evidence for a security finding (requests, responses, screenshots, logs)
	NodeTypeEvidence = "evidence"
	// Mitigation - Security control, patch, or remediation measure for a finding
	NodeTypeMitigation = "mitigation"
	// Tactic - Attack tactic representing a high-level adversary goal
	NodeTypeTactic = "tactic"
	// Technique - Attack technique from Gibson taxonomy
	NodeTypeTechnique = "technique"
)

// Relationship type constants
// These constants define the canonical relationship types in the GraphRAG taxonomy.
const (
	// ========== Core Execution Relationships ==========
	// PART_OF - Agent run is part of a mission
	RelTypePartOf = "PART_OF"
	// PART_OF_MISSION - Direct link to mission for traceability
	RelTypePartOfMission = "PART_OF_MISSION"
	// DELEGATED_TO - Mission or agent delegates work to another agent run
	RelTypeDelegatedTo = "DELEGATED_TO"
	// EXECUTED_BY - Tool execution was performed by an agent run
	RelTypeExecutedBy = "EXECUTED_BY"
	// DISCOVERED - Agent run discovered an asset
	RelTypeDiscovered = "DISCOVERED"
	// PRODUCED - Tool execution produced a finding
	RelTypeProduced = "PRODUCED"
	// MADE_CALL - LLM call was made by an agent run
	RelTypeMadeCall = "MADE_CALL"
	// GENERATED_BY - Intelligence was generated by an LLM call
	RelTypeGeneratedBy = "GENERATED_BY"
	// ANALYZES - Intelligence report analyzes assets or findings
	RelTypeAnalyzes = "ANALYZES"
	// BELONGS_TO - Entity belongs to a parent entity (MissionRun -> Mission, discovered nodes -> MissionRun)
	RelTypeBelongsTo = "BELONGS_TO"

	// ========== Asset Hierarchy Relationships ==========
	// HAS_SUBDOMAIN - Domain has a subdomain
	RelTypeHasSubdomain = "HAS_SUBDOMAIN"
	// RESOLVES_TO - Domain or subdomain resolves to an IP address (host)
	RelTypeResolvesTo = "RESOLVES_TO"
	// HAS_PORT - Host has an open port
	RelTypeHasPort = "HAS_PORT"
	// RUNS_SERVICE - Port runs a specific service
	RelTypeRunsService = "RUNS_SERVICE"
	// HAS_ENDPOINT - Service has a web endpoint or URL
	RelTypeHasEndpoint = "HAS_ENDPOINT"
	// USES_TECHNOLOGY - Service or endpoint uses a specific technology or framework
	RelTypeUsesTechnology = "USES_TECHNOLOGY"
	// SERVES_CERTIFICATE - Host serves a TLS/SSL certificate
	RelTypeServesCertificate = "SERVES_CERTIFICATE"
	// HOSTS - Cloud asset hosts a service or host instance
	RelTypeHosts = "HOSTS"

	// ========== Finding Relationships ==========
	// AFFECTS - Finding affects a specific asset (endpoint, service, host, or technology)
	RelTypeAffects = "AFFECTS"
	// EXPLOITS - Finding exploits a vulnerability in a specific technology or service
	RelTypeExploits = "EXPLOITS"
	// USES_TECHNIQUE - Finding demonstrates the use of a specific attack technique
	RelTypeUsesTechnique = "USES_TECHNIQUE"
	// HAS_EVIDENCE - Finding is supported by evidence (request, response, screenshot, etc.)
	RelTypeHasEvidence = "HAS_EVIDENCE"
	// LEADS_TO - Finding leads to another finding in an attack chain
	RelTypeLeadsTo = "LEADS_TO"
	// SIMILAR_TO - Finding is similar to another finding (bidirectional)
	RelTypeSimilarTo = "SIMILAR_TO"
	// MITIGATES - Mitigation addresses a specific finding
	RelTypeMitigates = "MITIGATES"

	// ========== Network Relationships ==========
	// ROUTES_TO - Router routes traffic to destination
	RelTypeRoutesTo = "ROUTES_TO"
	// FILTERS - Firewall filters traffic
	RelTypeFilters = "FILTERS"
	// TERMINATES_AT - VPN or tunnel terminates at endpoint
	RelTypeTerminatesAt = "TERMINATES_AT"
	// PEERS_WITH - BGP or routing peer relationship
	RelTypePeersWith = "PEERS_WITH"
	// LOAD_BALANCES - Load balancer distributes to backend
	RelTypeLoadBalances = "LOAD_BALANCES"
	// PROXIES_TO - Proxy forwards to backend
	RelTypeProxiesTo = "PROXIES_TO"
	// CONNECTS_VIA - Connection through network path
	RelTypeConnectsVia = "CONNECTS_VIA"

	// ========== Web/API Relationships ==========
	// HAS_PARAMETER - Endpoint has query or path parameter
	RelTypeHasParameter = "HAS_PARAMETER"
	// HAS_HEADER - Request has HTTP header
	RelTypeHasHeader = "HAS_HEADER"
	// HAS_COOKIE - Request has cookie
	RelTypeHasCookie = "HAS_COOKIE"
	// ACCEPTS_CONTENT - Endpoint accepts content type
	RelTypeAcceptsContent = "ACCEPTS_CONTENT"
	// RETURNS_CONTENT - Endpoint returns content type
	RelTypeReturnsContent = "RETURNS_CONTENT"
	// RATE_LIMITED_BY - Endpoint rate limited by policy
	RelTypeRateLimitedBy = "RATE_LIMITED_BY"
	// SECURED_BY_CORS - Endpoint secured by CORS policy
	RelTypeSecuredByCORS = "SECURED_BY_CORS"

	// ========== Identity Relationships ==========
	// HAS_MEMBER - Group has user member
	RelTypeHasMember = "HAS_MEMBER"
	// HAS_PERMISSION - Role or user has permission
	RelTypeHasPermission = "HAS_PERMISSION"
	// GRANTS_ACCESS - Policy grants access to resource
	RelTypeGrantsAccess = "GRANTS_ACCESS"
	// AUTHENTICATES_VIA - User authenticates via provider
	RelTypeAuthenticatesVia = "AUTHENTICATES_VIA"
	// ASSUMES_ROLE - User or service assumes role
	RelTypeAssumesRole = "ASSUMES_ROLE"
	// MANAGES_POLICY - Entity manages policy
	RelTypeManagesPolicy = "MANAGES_POLICY"
	// SCOPED_TO - Token or credential scoped to resource
	RelTypeScopedTo = "SCOPED_TO"

	// ========== AI/LLM Relationships ==========
	// USES_MODEL - Application uses LLM model
	RelTypeUsesModel = "USES_MODEL"
	// DEPLOYED_AS - Model deployed as endpoint
	RelTypeDeployedAs = "DEPLOYED_AS"
	// HAS_SYSTEM_PROMPT - Agent has system prompt
	RelTypeHasSystemPrompt = "HAS_SYSTEM_PROMPT"
	// PROTECTED_BY - LLM protected by guardrail
	RelTypeProtectedBy = "PROTECTED_BY"
	// FILTERS_WITH - LLM filters with content filter
	RelTypeFiltersWith = "FILTERS_WITH"
	// GENERATES_RESPONSE - LLM generates response
	RelTypeGeneratesResponse = "GENERATES_RESPONSE"
	// FINE_TUNED_FROM - Model fine-tuned from base model
	RelTypeFineTunedFrom = "FINE_TUNED_FROM"

	// ========== Agent Relationships ==========
	// HAS_TOOL - Agent has access to tool
	RelTypeHasTool = "HAS_TOOL"
	// HAS_MEMORY - Agent has memory store
	RelTypeHasMemory = "HAS_MEMORY"
	// EXECUTES_CHAIN - Agent executes chain
	RelTypeExecutesChain = "EXECUTES_CHAIN"
	// RUNS_WORKFLOW - Agent runs workflow
	RelTypeRunsWorkflow = "RUNS_WORKFLOW"
	// DELEGATES_TASK - Agent delegates task to another
	RelTypeDelegatesTask = "DELEGATES_TASK"
	// STORES_IN_MEMORY - Agent stores data in memory
	RelTypeStoresInMemory = "STORES_IN_MEMORY"
	// PLANS_STEP - Agent plans next step
	RelTypePlansStep = "PLANS_STEP"
	// PRODUCES_ARTIFACT - Agent produces artifact
	RelTypeProducesArtifact = "PRODUCES_ARTIFACT"
	// HAS_REASONING_STEP - Agent run has a reasoning step
	RelTypeHasReasoningStep = "HAS_REASONING_STEP"
	// HAS_MEMORY_ENTRY - Agent run has a memory entry
	RelTypeHasMemoryEntry = "HAS_MEMORY_ENTRY"

	// ========== MCP Relationships ==========
	// PROVIDES_TOOL - MCP server provides tool
	RelTypeProvidesTool = "PROVIDES_TOOL"
	// PROVIDES_RESOURCE - MCP server provides resource
	RelTypeProvidesResource = "PROVIDES_RESOURCE"
	// PROVIDES_PROMPT - MCP server provides prompt
	RelTypeProvidesPrompt = "PROVIDES_PROMPT"
	// CONNECTS_TO_SERVER - MCP client connects to server
	RelTypeConnectsToServer = "CONNECTS_TO_SERVER"
	// USES_TRANSPORT - MCP uses transport mechanism
	RelTypeUsesTransport = "USES_TRANSPORT"
	// SUPPORTS_CAPABILITY - MCP server supports capability
	RelTypeSupportsCapability = "SUPPORTS_CAPABILITY"

	// ========== RAG Relationships ==========
	// INDEXED_IN - Document indexed in vector store
	RelTypeIndexedIn = "INDEXED_IN"
	// CHUNKED_FROM - Chunk created from document
	RelTypeChunkedFrom = "CHUNKED_FROM"
	// EMBEDDED_AS - Text embedded as vector
	RelTypeEmbeddedAs = "EMBEDDED_AS"
	// RETRIEVED_BY - Document retrieved by query
	RelTypeRetrievedBy = "RETRIEVED_BY"
	// RERANKED_BY - Results reranked by model
	RelTypeRerankedBy = "RERANKED_BY"
	// FEEDS_INTO - Data feeds into pipeline
	RelTypeFeedsInto = "FEEDS_INTO"

	// ========== Data Relationships ==========
	// HAS_TABLE - Database has table
	RelTypeHasTable = "HAS_TABLE"
	// HAS_COLUMN - Table has column
	RelTypeHasColumn = "HAS_COLUMN"
	// HAS_INDEX - Table has index
	RelTypeHasIndex = "HAS_INDEX"
	// STORED_IN - Data stored in storage
	RelTypeStoredIn = "STORED_IN"
	// ENQUEUED_IN - Message enqueued in queue
	RelTypeEnqueuedIn = "ENQUEUED_IN"
	// PUBLISHED_TO - Message published to topic
	RelTypePublishedTo = "PUBLISHED_TO"
	// CACHED_IN - Data cached in cache layer
	RelTypeCachedIn = "CACHED_IN"

	// ========== Kubernetes Relationships ==========
	// DEPLOYED_IN - Resource deployed in namespace
	RelTypeDeployedIn = "DEPLOYED_IN"
	// MOUNTED_BY - Volume mounted by pod
	RelTypeMountedBy = "MOUNTED_BY"
	// BOUND_TO - Resource bound to another
	RelTypeBoundTo = "BOUND_TO"
	// SECURED_BY_POLICY - Resource secured by policy
	RelTypeSecuredByPolicy = "SECURED_BY_POLICY"
	// LIMITED_BY - Resource limited by quota or limit
	RelTypeLimitedBy = "LIMITED_BY"
	// SCHEDULED_ON - Pod scheduled on node
	RelTypeScheduledOn = "SCHEDULED_ON"

	// ========== Cloud Relationships ==========
	// HOSTED_IN_VPC - Resource hosted in VPC
	RelTypeHostedInVPC = "HOSTED_IN_VPC"
	// IN_SUBNET - Resource in subnet
	RelTypeInSubnet = "IN_SUBNET"
	// PROTECTED_BY_SG - Resource protected by security group
	RelTypeProtectedBySG = "PROTECTED_BY_SG"
	// SERVED_BY_CDN - Content served by CDN
	RelTypeServedByCDN = "SERVED_BY_CDN"
	// ENCRYPTED_BY - Data encrypted by KMS key
	RelTypeEncryptedBy = "ENCRYPTED_BY"
	// MONITORED_BY - Resource monitored by metric/alarm
	RelTypeMonitoredBy = "MONITORED_BY"
	// LOGGED_TO - Activity logged to audit trail
	RelTypeLoggedTo = "LOGGED_TO"
)

// Gibson-native Tactic ID constants
// These replace MITRE ATT&CK tactics with Gibson-specific identifiers
const (
	// GIB-TA01: Reconnaissance - Information gathering about target
	TacticReconnaissance = "GIB-TA01"
	// GIB-TA02: Resource Development - Building attack infrastructure
	TacticResourceDevelopment = "GIB-TA02"
	// GIB-TA03: Initial Access - Gaining initial foothold in target system
	TacticInitialAccess = "GIB-TA03"
	// GIB-TA04: Execution - Running malicious code on target
	TacticExecution = "GIB-TA04"
	// GIB-TA05: Persistence - Maintaining access over time
	TacticPersistence = "GIB-TA05"
	// GIB-TA06: Privilege Escalation - Gaining higher-level permissions
	TacticPrivilegeEscalation = "GIB-TA06"
	// GIB-TA07: Defense Evasion - Avoiding detection by security controls
	TacticDefenseEvasion = "GIB-TA07"
	// GIB-TA08: Credential Access - Stealing account credentials
	TacticCredentialAccess = "GIB-TA08"
	// GIB-TA09: Discovery - Exploring the target environment
	TacticDiscovery = "GIB-TA09"
	// GIB-TA10: Lateral Movement - Moving through the network
	TacticLateralMovement = "GIB-TA10"
	// GIB-TA11: Collection - Gathering target data of interest
	TacticCollection = "GIB-TA11"
	// GIB-TA12: Exfiltration - Stealing data from target
	TacticExfiltration = "GIB-TA12"
	// GIB-TA13: Impact - Disrupting or destroying target systems
	TacticImpact = "GIB-TA13"
	// GIB-TA14: AI Manipulation - AI/LLM-specific attack techniques
	TacticAIManipulation = "GIB-TA14"
)

// Gibson-native Technique ID constants (AI-focused)
// These are Gibson-specific techniques for AI/LLM security testing
const (
	// GIB-T1001: Prompt Injection - Direct injection of malicious prompts
	TechniquePromptInjection = "GIB-T1001"
	// GIB-T1002: Jailbreak - Bypassing model safety restrictions
	TechniqueJailbreak = "GIB-T1002"
	// GIB-T1003: System Prompt Extraction - Extracting hidden system prompts
	TechniqueSystemPromptExtraction = "GIB-T1003"
	// GIB-T1004: Training Data Extraction - Extracting memorized training data
	TechniqueTrainingDataExtraction = "GIB-T1004"
	// GIB-T1005: Model Inversion - Inferring training data from model behavior
	TechniqueModelInversion = "GIB-T1005"
	// GIB-T1006: RAG Poisoning - Poisoning RAG knowledge base with malicious data
	TechniqueRAGPoisoning = "GIB-T1006"
	// GIB-T1007: Citation Injection - Injecting false citations into RAG responses
	TechniqueCitationInjection = "GIB-T1007"
	// GIB-T1008: Tool Abuse - Abusing agent tools for malicious purposes
	TechniqueToolAbuse = "GIB-T1008"
	// GIB-T1009: Agent Hijacking - Taking control of autonomous agents
	TechniqueAgentHijacking = "GIB-T1009"
	// GIB-T1010: MCP Tool Injection - Injecting malicious MCP tools
	TechniqueMCPToolInjection = "GIB-T1010"
	// GIB-T1011: Memory Poisoning - Poisoning agent memory stores
	TechniqueMemoryPoisoning = "GIB-T1011"
	// GIB-T1012: Guardrail Bypass - Bypassing safety guardrails
	TechniqueGuardrailBypass = "GIB-T1012"
	// GIB-T1013: Model DoS - Denial of service attacks on models
	TechniqueModelDoS = "GIB-T1013"
	// GIB-T1014: Encoding Obfuscation - Using encoding to evade filters
	TechniqueEncodingObfuscation = "GIB-T1014"
	// GIB-T1015: Language Switching - Switching languages to evade detection
	TechniqueLanguageSwitching = "GIB-T1015"
	// GIB-T1016: Token Smuggling - Token-level attack techniques
	TechniqueTokenSmuggling = "GIB-T1016"
	// GIB-T1017: Instruction Hierarchy - Exploiting instruction priority conflicts
	TechniqueInstructionHierarchy = "GIB-T1017"
	// GIB-T1018: Payload Splitting - Splitting payloads across multiple turns
	TechniquePayloadSplitting = "GIB-T1018"
	// GIB-T1019: Indirect Prompt Injection - Injection via external data sources
	TechniqueIndirectPromptInjection = "GIB-T1019"
	// GIB-T1020: Multi-Modal Injection - Injection via images, audio, or video
	TechniqueMultiModalInjection = "GIB-T1020"
)

// Common property name constants
const (
	// ========== Core Properties ==========
	PropName        = "name"
	PropTitle       = "title"
	PropDescription = "description"
	PropCategory    = "category"
	PropTimestamp   = "timestamp"

	// ========== Finding Properties ==========
	PropSeverity   = "severity"
	PropConfidence = "confidence"

	// ========== Network Properties ==========
	PropURL      = "url"
	PropIP       = "ip"
	PropPort     = "port"   // Generic port property (for backwards compatibility)
	PropNumber   = "number" // Port number property (taxonomy-compliant for Port nodes)
	PropProtocol = "protocol"
	PropHostID   = "host_id" // Host ID property for Port nodes
	PropState    = "state"   // State property (open, closed, filtered)
	PropPortID   = "port_id" // For service nodes referencing their port

	// ========== Web/API Properties ==========
	PropMethod     = "method"
	PropStatusCode = "status_code"
	PropBaseURL    = "base_url" // For API nodes

	// ========== Asset Properties ==========
	PropParentDomain = "parent_domain" // For subdomain nodes

	// ========== Execution Properties ==========
	PropAgentName  = "agent_name"   // For agent_run nodes
	PropRunNumber  = "run_number"   // For agent_run nodes
	PropMissionID  = "mission_id"   // For linking to missions
	PropToolName   = "tool_name"    // For tool_execution nodes
	PropAgentRunID = "agent_run_id" // For tool_execution nodes
	PropModel      = "model"        // For llm_call nodes

	// ========== AI/LLM Properties ==========
	PropProvider      = "provider"       // LLM provider (openai, anthropic, etc.)
	PropModelID       = "model_id"       // Model identifier
	PropContextWindow = "context_window" // Context window size
	PropMaxTokens     = "max_tokens"     // Maximum token limit
	PropCapabilities  = "capabilities"   // Model capabilities

	// ========== MCP Properties ==========
	PropTransport   = "transport"    // MCP transport type (stdio, sse, http)
	PropInputSchema = "input_schema" // Tool input schema
	PropURI         = "uri"          // Resource URI
	PropMimeType    = "mime_type"    // Content MIME type

	// ========== RAG Properties ==========
	PropDimensions     = "dimensions"      // Embedding dimensions
	PropDistanceMetric = "distance_metric" // Distance metric (cosine, euclidean)
	PropChunkIndex     = "chunk_index"     // Chunk position in document
	PropEmbeddingID    = "embedding_id"    // Embedding identifier

	// ========== Identity Properties ==========
	PropPrincipal   = "principal"   // Principal identifier (user, service account)
	PropScope       = "scope"       // Permission or token scope
	PropExpiry      = "expiry"      // Expiration timestamp
	PropPermissions = "permissions" // List of permissions

	// ========== Cloud Properties ==========
	PropRegion           = "region"            // Cloud region (us-east-1, etc.)
	PropAvailabilityZone = "availability_zone" // Availability zone
	PropInstanceType     = "instance_type"     // Instance type (t2.micro, etc.)
	PropArn              = "arn"               // AWS ARN or similar identifier
)
